import { useEffect, useMemo, useState, type ReactNode } from "react";
import {
  Activity,
  AlertCircle,
  ArrowLeft,
  BatteryCharging,
  BatteryLow,
  BatteryMedium,
  Bell,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronRight,
  CircleAlert,
  Clock3,
  CloudOff,
  Info,
  Languages,
  Leaf,
  Menu,
  Phone,
  RefreshCw,
  ScanLine,
  Search,
  Signal,
  ShieldCheck,
  Sparkles,
  Stethoscope,
  Sun,
  TrendingUp,
  UserRound,
  Wifi,
  XCircle,
} from "lucide-react";

export type Language = "en" | "hi" | "mr" | "gu" | "pa" | "kn" | "ta" | "te";
export type Risk = "low" | "medium" | "high";
export type View = "home" | "alerts" | "about" | "cow" | "vet" | "farm" | "profile";
export type Validation = "active" | "confirmed" | "false-alarm" | "resolved";
export type SensorState = "connected" | "stale" | "low-battery";

export type SensorTelemetry = {
  ec: number;
  temperature: number;
  battery: number;
  state: SensorState;
  lastContact: string;
};

export type Cow = {
  id: string;
  name: string;
  tag: string;
  farm: string;
  breed: string;
  risk: Risk;
  score: number;
  probability: number | null;
  checked: string;
  recommendation: string;
  history: number[];
  historyDays: string[];
  sensor: SensorTelemetry;
  treatmentStatus?: "under-treatment" | "none";
};

export type AlertItem = {
  id: string;
  cowId: string;
  date: string;
  time: string;
  risk: Risk;
  title: string;
  body: string;
  validation: Validation;
};

export type StateOption = { state: string; native: string; language: Language; languageLabel: string };

export const stateOptions: StateOption[] = [
  { state: "Maharashtra", native: "महाराष्ट्र", language: "mr", languageLabel: "मराठी" },
  { state: "Gujarat", native: "ગુજરાત", language: "gu", languageLabel: "ગુજરાતી" },
  { state: "Punjab", native: "ਪੰਜਾਬ", language: "pa", languageLabel: "ਪੰਜਾਬੀ" },
  { state: "Karnataka", native: "ಕರ್ನಾಟಕ", language: "kn", languageLabel: "ಕನ್ನಡ" },
  { state: "Tamil Nadu", native: "தமிழ்நாடு", language: "ta", languageLabel: "தமிழ்" },
  { state: "Andhra Pradesh", native: "ఆంధ్ర ప్రదేశ్", language: "te", languageLabel: "తెలుగు" },
  { state: "Telangana", native: "తెలంగాణ", language: "te", languageLabel: "తెలుగు" },
  { state: "Uttar Pradesh", native: "उत्तर प्रदेश", language: "hi", languageLabel: "हिन्दी" },
  { state: "Bihar", native: "बिहार", language: "hi", languageLabel: "हिन्दी" },
  { state: "Rajasthan", native: "राजस्थान", language: "hi", languageLabel: "हिन्दी" },
  { state: "Madhya Pradesh", native: "मध्य प्रदेश", language: "hi", languageLabel: "हिन्दी" },
  { state: "Kerala", native: "കേരളം", language: "en", languageLabel: "English" },
  { state: "West Bengal", native: "পশ্চিমবঙ্গ", language: "en", languageLabel: "English" },
  { state: "Odisha", native: "ଓଡ଼ିଶା", language: "en", languageLabel: "English" },
  { state: "Assam", native: "অসম", language: "en", languageLabel: "English" },
  { state: "Goa", native: "गोवा", language: "en", languageLabel: "English" },
  { state: "Arunachal Pradesh", native: "Arunachal Pradesh", language: "en", languageLabel: "English" },
  { state: "Chhattisgarh", native: "छत्तीसगढ़", language: "hi", languageLabel: "हिन्दी" },
  { state: "Haryana", native: "हरियाणा", language: "hi", languageLabel: "हिन्दी" },
  { state: "Himachal Pradesh", native: "हिमाचल प्रदेश", language: "hi", languageLabel: "हिन्दी" },
  { state: "Jharkhand", native: "झारखंड", language: "hi", languageLabel: "हिन्दी" },
  { state: "Manipur", native: "মণিপুর", language: "en", languageLabel: "English" },
  { state: "Meghalaya", native: "Meghalaya", language: "en", languageLabel: "English" },
  { state: "Mizoram", native: "Mizoram", language: "en", languageLabel: "English" },
  { state: "Nagaland", native: "Nagaland", language: "en", languageLabel: "English" },
  { state: "Sikkim", native: "सिक्किम", language: "en", languageLabel: "English" },
  { state: "Tripura", native: "ত্রিপুরা", language: "en", languageLabel: "English" },
  { state: "Uttarakhand", native: "उत्तराखंड", language: "hi", languageLabel: "हिन्दी" },
  { state: "Delhi", native: "दिल्ली", language: "hi", languageLabel: "हिन्दी" },
  { state: "Jammu and Kashmir", native: "जम्मू और कश्मीर", language: "en", languageLabel: "English" },
  { state: "Ladakh", native: "लद्दाख", language: "en", languageLabel: "English" },
  { state: "Puducherry", native: "புதுச்சேரி", language: "en", languageLabel: "English" },
  { state: "Chandigarh", native: "ਚੰਡੀਗੜ੍ਹ", language: "en", languageLabel: "English" },
  { state: "Andaman and Nicobar Islands", native: "Andaman and Nicobar Islands", language: "en", languageLabel: "English" },
  { state: "Dadra and Nagar Haveli and Daman and Diu", native: "Dadra and Nagar Haveli and Daman and Diu", language: "en", languageLabel: "English" },
  { state: "Lakshadweep", native: "Lakshadweep", language: "en", languageLabel: "English" },
  { state: "Other state / UT", native: "Other state / UT", language: "en", languageLabel: "English" },
];

// Deliberate scope: unsupported Hindi-belt states are mapped to Hindi; other unsupported states/UTs fall back to English.
export function resolveStateLanguage(state: StateOption): Language {
  return state.language;
}

export const cowsSeed: Cow[] = [
  {
    id: "cow-1",
    name: "Lakshmi",
    tag: "Cow #03",
    farm: "Sita Devi’s Dairy",
    breed: "Gir cross",
    risk: "high",
    score: 86,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [18, 20, 23, 27, 29, 32, 36, 42, 49, 57, 64, 71, 78, 86],
    historyDays: ["Aug 24", "25", "26", "27", "28", "29", "30", "31", "Sep 1", "2", "3", "4", "5", "Today"],
    sensor: { ec: 7.82, temperature: 39.4, battery: 64, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-2",
    name: "Gauri",
    tag: "Cow #07",
    farm: "Sita Devi’s Dairy",
    breed: "Sahiwal",
    risk: "medium",
    score: 54,
    probability: null,
    checked: "Today, 6:42 AM",
    recommendation: "",
    history: [35, 38, 36, 40, 39, 44, 42, 46, 49, 48, 51, 50, 53, 54],
    historyDays: ["Aug 24", "25", "26", "27", "28", "29", "30", "31", "Sep 1", "2", "3", "4", "5", "Today"],
    sensor: { ec: 6.48, temperature: 39.0, battery: 42, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-3",
    name: "Radha",
    tag: "Cow #11",
    farm: "Sita Devi’s Dairy",
    breed: "Jersey cross",
    risk: "low",
    score: 18,
    probability: null,
    checked: "Today, 6:45 AM",
    recommendation: "",
    history: [22, 20, 21, 19, 20, 18, 17, 19, 18, 16, 17, 18, 17, 18],
    historyDays: ["Aug 24", "25", "26", "27", "28", "29", "30", "31", "Sep 1", "2", "3", "4", "5", "Today"],
    sensor: { ec: 4.36, temperature: 38.5, battery: 81, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-4",
    name: "Kamdhenu",
    tag: "Cow #14",
    farm: "Sita Devi’s Dairy",
    breed: "Tharparkar",
    risk: "medium",
    score: 47,
    probability: null,
    checked: "Yesterday, 6:35 AM",
    recommendation: "",
    history: [42, 39, 44, 41, 45, 43, 40, 45, 44, 46, 48, 45, 47, 47],
    historyDays: ["Aug 24", "25", "26", "27", "28", "29", "30", "31", "Sep 1", "2", "3", "4", "5", "Today"],
    sensor: { ec: 6.12, temperature: 38.9, battery: 11, state: "low-battery", lastContact: "Just now" },
  },
  {
    id: "cow-5",
    name: "Nandini",
    tag: "Cow #18",
    farm: "Sita Devi’s Dairy",
    breed: "Gir",
    risk: "low",
    score: 12,
    probability: null,
    checked: "Yesterday, 6:31 AM",
    recommendation: "",
    history: [14, 13, 14, 12, 11, 12, 14, 13, 12, 11, 13, 12, 11, 12],
    historyDays: ["Aug 24", "25", "26", "27", "28", "29", "30", "31", "Sep 1", "2", "3", "4", "5", "Today"],
    sensor: { ec: 4.12, temperature: 38.4, battery: 28, state: "stale", lastContact: "2 days ago" },
  },
  {
    id: "cow-6",
    name: "Bela",
    tag: "Cow #52",
    farm: "Rameshwar Dairy",
    breed: "Gir cross",
    risk: "medium",
    score: 58,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [58, 62, 64, 61, 59, 56, 59, 59, 57, 60, 62, 59, 61, 58],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.79, temperature: 38.0, battery: 55, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-7",
    name: "Champa",
    tag: "Cow #39",
    farm: "Rameshwar Dairy",
    breed: "Gir cross",
    risk: "medium",
    score: 57,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [60, 61, 58, 62, 58, 59, 56, 58, 57, 61, 58, 54, 52, 57],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.79, temperature: 38.0, battery: 75, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-8",
    name: "Hira",
    tag: "Cow #19",
    farm: "Rameshwar Dairy",
    breed: "Gir cross",
    risk: "low",
    score: 17,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [8, 10, 12, 13, 8, 12, 16, 11, 13, 17, 18, 15, 17, 17],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.17, temperature: 38.3, battery: 34, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-9",
    name: "Ganga",
    tag: "Cow #41",
    farm: "Kisan Milk Cooperative",
    breed: "Gir cross",
    risk: "medium",
    score: 47,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [49, 44, 40, 38, 39, 38, 42, 39, 39, 40, 43, 44, 45, 47],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.35, temperature: 38.2, battery: 62, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-10",
    name: "Jamuna",
    tag: "Cow #23",
    farm: "Kisan Milk Cooperative",
    breed: "Gir cross",
    risk: "low",
    score: 25,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [26, 21, 18, 17, 21, 22, 24, 28, 31, 29, 33, 32, 29, 25],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.06, temperature: 38.3, battery: 61, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-11",
    name: "Saraswati",
    tag: "Cow #42",
    farm: "Kisan Milk Cooperative",
    breed: "Gir cross",
    risk: "medium",
    score: 54,
    probability: null,
    checked: "2 days ago",
    recommendation: "",
    history: [39, 40, 42, 46, 50, 50, 46, 45, 42, 44, 44, 48, 52, 54],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.52, temperature: 38.1, battery: 53, state: "stale", lastContact: "2 days ago" },
  },
  {
    id: "cow-12",
    name: "Narmada",
    tag: "Cow #67",
    farm: "Kisan Milk Cooperative",
    breed: "Gir cross",
    risk: "low",
    score: 36,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [32, 32, 30, 33, 34, 33, 34, 30, 35, 35, 32, 32, 32, 36],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.94, temperature: 38.3, battery: 40, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-13",
    name: "Sundari",
    tag: "Cow #58",
    farm: "Prakash Farm",
    breed: "Gir cross",
    risk: "low",
    score: 37,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [35, 35, 38, 34, 29, 31, 36, 38, 35, 30, 33, 37, 33, 37],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.98, temperature: 38.3, battery: 66, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-14",
    name: "Rani",
    tag: "Cow #96",
    farm: "Prakash Farm",
    breed: "Gir cross",
    risk: "low",
    score: 29,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [32, 34, 34, 31, 30, 32, 34, 29, 29, 26, 27, 28, 32, 29],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.73, temperature: 38.4, battery: 69, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-15",
    name: "Gomati",
    tag: "Cow #33",
    farm: "Anjali Dairy",
    breed: "Gir cross",
    risk: "low",
    score: 14,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [7, 7, 5, 7, 5, 5, 8, 12, 12, 15, 15, 18, 19, 14],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.73, temperature: 38.0, battery: 38, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-16",
    name: "Kaushalya",
    tag: "Cow #49",
    farm: "Anjali Dairy",
    breed: "Gir cross",
    risk: "low",
    score: 18,
    probability: null,
    checked: "2 days ago",
    recommendation: "",
    history: [7, 5, 8, 10, 11, 12, 15, 15, 19, 14, 17, 15, 18, 18],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.13, temperature: 38.2, battery: 69, state: "stale", lastContact: "2 days ago" },
  },
  {
    id: "cow-17",
    name: "Sita",
    tag: "Cow #16",
    farm: "Anjali Dairy",
    breed: "Gir cross",
    risk: "low",
    score: 35,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [42, 38, 34, 30, 33, 34, 37, 35, 39, 35, 30, 35, 37, 35],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.62, temperature: 38.3, battery: 47, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-18",
    name: "Savitri",
    tag: "Cow #93",
    farm: "Anjali Dairy",
    breed: "Gir cross",
    risk: "low",
    score: 27,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [16, 14, 18, 16, 12, 13, 17, 20, 19, 15, 18, 21, 22, 27],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.01, temperature: 38.3, battery: 76, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-19",
    name: "Laxmi",
    tag: "Cow #71",
    farm: "Anjali Dairy",
    breed: "Gir cross",
    risk: "medium",
    score: 54,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [56, 52, 56, 53, 53, 58, 58, 62, 59, 55, 57, 55, 59, 54],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.43, temperature: 38.2, battery: 56, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-20",
    name: "Roopa",
    tag: "Cow #54",
    farm: "Balram Farm",
    breed: "Gir cross",
    risk: "medium",
    score: 50,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [59, 54, 51, 49, 48, 46, 46, 51, 49, 46, 46, 48, 49, 50],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.38, temperature: 38.5, battery: 37, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-21",
    name: "Tara",
    tag: "Cow #28",
    farm: "Balram Farm",
    breed: "Gir cross",
    risk: "low",
    score: 10,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [7, 10, 13, 10, 10, 13, 12, 8, 5, 6, 8, 10, 8, 10],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.84, temperature: 38.1, battery: 41, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-22",
    name: "Tulsi",
    tag: "Cow #72",
    farm: "Balram Farm",
    breed: "Gir cross",
    risk: "low",
    score: 31,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [42, 42, 43, 46, 42, 37, 33, 31, 33, 36, 34, 36, 33, 31],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.99, temperature: 38.3, battery: 46, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-23",
    name: "Dharti",
    tag: "Cow #35",
    farm: "Balram Farm",
    breed: "Gir cross",
    risk: "high",
    score: 85,
    probability: null,
    checked: "2 days ago",
    recommendation: "",
    history: [79, 83, 79, 74, 73, 77, 73, 77, 82, 79, 79, 82, 86, 85],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 7.21, temperature: 39.5, battery: 52, state: "stale", lastContact: "2 days ago" },
  },
  {
    id: "cow-24",
    name: "Shanti",
    tag: "Cow #21",
    farm: "Om Prakash Dairy",
    breed: "Gir cross",
    risk: "medium",
    score: 42,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [46, 48, 47, 45, 48, 44, 44, 42, 47, 47, 44, 46, 44, 42],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.93, temperature: 38.5, battery: 72, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-25",
    name: "Jyoti",
    tag: "Cow #78",
    farm: "Om Prakash Dairy",
    breed: "Gir cross",
    risk: "low",
    score: 10,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [5, 8, 10, 5, 8, 5, 5, 5, 5, 9, 10, 13, 10, 10],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.53, temperature: 38.2, battery: 75, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-26",
    name: "Meera",
    tag: "Cow #64",
    farm: "Kaveri Dairy",
    breed: "Gir cross",
    risk: "low",
    score: 22,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [15, 20, 24, 24, 20, 16, 13, 15, 17, 13, 17, 18, 22, 22],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.53, temperature: 38.4, battery: 74, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-27",
    name: "Malti",
    tag: "Cow #36",
    farm: "Kaveri Dairy",
    breed: "Gir cross",
    risk: "low",
    score: 25,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [28, 28, 29, 28, 31, 27, 32, 28, 27, 27, 29, 26, 22, 25],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.61, temperature: 38.1, battery: 48, state: "connected", lastContact: "Just now" },
  },
  {
    id: "cow-28",
    name: "Bhavani",
    tag: "Cow #29",
    farm: "Kaveri Dairy",
    breed: "Gir cross",
    risk: "low",
    score: 19,
    probability: null,
    checked: "Today, 6:40 AM",
    recommendation: "",
    history: [16, 17, 16, 12, 16, 16, 16, 15, 12, 15, 16, 21, 23, 19],
    historyDays: ["Aug 24","25","26","27","28","29","30","31","Sep 1","2","3","4","5","Today"],
    sensor: { ec: 4.17, temperature: 38.3, battery: 75, state: "connected", lastContact: "Just now" },
  },
];

export const cowsSeedInitialized = cowsSeed;

export const alertsSeed: AlertItem[] = [
  {
    id: "alert-1",
    cowId: "cow-1",
    date: "Today",
    time: "6:40 AM",
    risk: "high",
    title: "Early signs detected in Lakshmi",
    body: "Risk has risen steadily for 5 days. Contact your vet today.",
    validation: "active",
  },
  {
    id: "alert-2",
    cowId: "cow-2",
    date: "Today",
    time: "6:42 AM",
    risk: "medium",
    title: "Gauri needs another check",
    body: "A small change was noticed. Check again tomorrow morning.",
    validation: "active",
  },
  {
    id: "alert-3",
    cowId: "cow-4",
    date: "Yesterday",
    time: "6:35 AM",
    risk: "medium",
    title: "Kamdhenu is being watched",
    body: "Her reading is steady but above her normal range.",
    validation: "active",
  },
  {
    id: "alert-4",
    cowId: "cow-3",
    date: "Sep 04",
    time: "6:39 AM",
    risk: "low",
    title: "Routine check complete",
    body: "Radha’s reading is healthy. No action needed.",
    validation: "resolved",
  },
];

export const copy = {
  en: {
    home: "My cows",
    alerts: "Alerts",
    about: "How it works",
    farmer: "Farmer view",
    vet: "Vet view",
    greeting: "Good morning, Sita",
    subtitle: "Here is your herd’s health today.",
    checkCows: "Check my cows",
    checking: "Checking readings…",
    addReading: "Add a reading",
    monitored: "Cows monitored",
    attention: "Need attention",
    healthy: "Healthy today",
    lastSynced: "Last synced 2 hours ago",
    offline: "Offline mode",
    online: "Online",
    high: "High risk",
    medium: "Watch closely",
    low: "Low risk",
    activeAlert: "Active alert",
    viewDetails: "View details",
    todayAt: "Checked today",
    recommendation: "Recommended action",
    history: "Risk history",
    trendTitle: "We noticed the change early",
    trendBody: "Lakshmi’s risk rose over the last 5 days. This is an early warning, before visible signs.",
    vetConfirmed: "Vet confirmed",
    falseAlarm: "False alarm",
    confirmed: "Confirmed",
    resolved: "Resolved",
    underTreatment: "Under treatment",
    underTreatmentRec: "Under vet treatment and active observation.",
    learnMore: "Learn more",
    switchToVet: "Switch to vet view",
    switchToFarmer: "Back to farmer view",
    menu: "Menu",
    selectCow: "Select a cow",
    activeAlerts: "Active alerts",
    farmsFlagged: "Farms flagged this week",
    casesMonth: "Confirmed cases this month",
    animals: "Animals monitored",
    sortRisk: "Sort by risk",
    allAlerts: "All alerts",
    highOnly: "High risk only",
    noAction: "No action needed — monitor as usual.",
    earlyWarning: "Early warning",
    demoNote: "Demo data · No hardware connected",
    aboutTitleLine1: "Know sooner.",
    aboutTitleLine2: "Care better.",
    aboutBody: "We check your cow’s milk for early signs of infection — days before you might notice anything yourself.",
    howOneTitle: "Check during milking",
    howOneBody: "The small sensor reads each cow while you already do your morning routine.",
    howTwoTitle: "Watch the change",
    howTwoBody: "We look at the pattern over time, not just one reading.",
    howThreeTitle: "Act early",
    howThreeBody: "A clear alert helps you speak to your vet before a problem grows.",
    aboutNoteTitle: "Built for real farm mornings.",
    aboutNoteBody: "Large buttons, simple colors, Hindi support, and offline-friendly readings keep Pashu Mitra useful in a cattle shed, not just on a stage.",
    phaseTwo: "Phase 2 roadmap · cooperative rollout",
    herdOverview: "Herd health overview",
    herdOverviewBody: "A clear picture across Sita Devi’s Dairy and nearby farms.",
    priorityList: "Priority list",
    animalsToReview: "Animals to review",
    selectedAnimal: "Selected animal",
    tableAnimal: "Animal",
    tableFarm: "Farm",
    tableRisk: "Risk",
    lastReading: "Last reading",
    tableAction: "Action",
    reviewed: "Reviewed",
    review: "Review",
    weekLabel: "Week 36 · 2026",
    readingCompletion: "Reading completion",
    cooperativeDesk: "Cooperative field desk",
    needsFollowup: "Needs follow-up",
    treatedEarly: "Both treated early",
    acrossFarms: "Across 8 farms",
    confirm: "Confirm",
    falseAlarmAction: "False alarm",
    noAnimalsMatch: "No animals match",
    riskChartNote: "Risk score over 14 days. A rising line prompts a timely physical check.",
  },
  hi: {
    home: "मेरी गायें",
    alerts: "सूचनाएं",
    about: "यह कैसे काम करता है",
    farmer: "किसान दृश्य",
    vet: "पशु चिकित्सक दृश्य",
    greeting: "सुप्रभात, सीता",
    subtitle: "आज आपके झुंड का स्वास्थ्य।",
    checkCows: "गायों की जांच करें",
    checking: "जांच हो रही है…",
    addReading: "रीडिंग जोड़ें",
    monitored: "निगरानी में",
    attention: "ध्यान दें",
    healthy: "आज स्वस्थ",
    lastSynced: "2 घंटे पहले सिंक हुआ",
    offline: "ऑफलाइन मोड",
    online: "ऑनलाइन",
    high: "अधिक जोखिम",
    medium: "ध्यान से देखें",
    low: "कम जोखिम",
    activeAlert: "सक्रिय सूचना",
    viewDetails: "विवरण देखें",
    todayAt: "आज जांची गई",
    recommendation: "सुझाई गई कार्रवाई",
    history: "जोखिम का इतिहास",
    trendTitle: "बदलाव जल्दी पता चला",
    trendBody: "लक्ष्मी का जोखिम पिछले 5 दिनों में बढ़ा है। यह दिखाई देने वाले लक्षणों से पहले की चेतावनी है।",
    vetConfirmed: "डॉक्टर ने पुष्टि की",
    falseAlarm: "गलत चेतावनी",
    confirmed: "पुष्टि हुई",
    resolved: "सुलझा हुआ",
    underTreatment: "उपचाराधीन",
    underTreatmentRec: "पशु चिकित्सक के इलाज और निगरानी में।",
    learnMore: "और जानें",
    switchToVet: "पशु चिकित्सक दृश्य",
    switchToFarmer: "किसान दृश्य पर वापस",
    menu: "मेनू",
    selectCow: "गाय चुनें",
    activeAlerts: "सक्रिय सूचनाएं",
    farmsFlagged: "इस सप्ताह जोखिम वाले फार्म",
    casesMonth: "इस महीने पुष्ट मामले",
    animals: "निगरानी में पशु",
    sortRisk: "जोखिम के अनुसार",
    allAlerts: "सभी सूचनाएं",
    highOnly: "केवल अधिक जोखिम",
    noAction: "कोई कार्रवाई नहीं — सामान्य निगरानी रखें।",
    earlyWarning: "जल्दी चेतावनी",
    demoNote: "डेमो डेटा · कोई हार्डवेयर जुड़ा नहीं",
    aboutTitleLine1: "जल्दी जानें।",
    aboutTitleLine2: "बेहतर देखभाल करें।",
    aboutBody: "हम आपकी गाय के दूध में संक्रमण के शुरुआती संकेत खोजते हैं — कई दिन पहले, जब आपको कुछ दिखाई भी नहीं देता।",
    howOneTitle: "दुहते समय जांचें",
    howOneBody: "छोटा सेंसर हर गाय को उसी सुबह की दिनचर्या के दौरान पढ़ता है।",
    howTwoTitle: "बदलाव पर नज़र रखें",
    howTwoBody: "हम केवल एक रीडिंग नहीं, बल्कि समय के साथ पैटर्न देखते हैं।",
    howThreeTitle: "जल्दी कदम उठाएं",
    howThreeBody: "एक साफ सूचना आपको समस्या बढ़ने से पहले डॉक्टर से बात करने में मदद करती है।",
    aboutNoteTitle: "असली खेत की सुबह के लिए बनाया गया।",
    aboutNoteBody: "बड़े बटन, सरल रंग, हिंदी सहायता और ऑफलाइन रीडिंग Pashu Mitra को खेत में उपयोगी बनाते हैं, सिर्फ मंच पर नहीं।",
    phaseTwo: "फेज़ 2 रोडमैप · सहकारी विस्तार",
    herdOverview: "झुंड के स्वास्थ्य का अवलोकन",
    herdOverviewBody: "सीता देवी के डेयरी और आसपास के फार्मों की स्पष्ट तस्वीर।",
    priorityList: "प्राथमिकता सूची",
    animalsToReview: "जिन पशुओं की समीक्षा करनी है",
    selectedAnimal: "चयनित पशु",
    tableAnimal: "पशु",
    tableFarm: "फार्म",
    tableRisk: "जोखिम",
    lastReading: "अंतिम रीडिंग",
    tableAction: "कार्रवाई",
    reviewed: "समीक्षा हुई",
    review: "समीक्षा करें",
    weekLabel: "सप्ताह 36 · 2026",
    readingCompletion: "रीडिंग पूर्णता",
    cooperativeDesk: "सहकारी फील्ड डेस्क",
    needsFollowup: "फॉलो-अप ज़रूरी",
    treatedEarly: "दोनों का जल्दी इलाज हुआ",
    acrossFarms: "8 फार्मों में",
    confirm: "पुष्टि करें",
    falseAlarmAction: "गलत चेतावनी",
    noAnimalsMatch: "कोई पशु मेल नहीं खाता",
    riskChartNote: "14 दिनों का जोखिम स्कोर। बढ़ती रेखा समय पर शारीरिक जांच का संकेत देती है।",
  },
};

export const localizedCopy: Record<Language, typeof copy.en> = {
  en: copy.en,
  hi: copy.hi,
  mr: { ...copy.en, home: "माझ्या गायी", alerts: "सूचना", about: "हे कसे काम करते", farmer: "शेतकरी दृश्य", vet: "पशुवैद्य दृश्य", greeting: "शुभ प्रभात, सीता", subtitle: "आज तुमच्या कळपाचे आरोग्य.", checkCows: "गायी तपासा", checking: "रीडिंग तपासत आहे…", monitored: "निगराणीतील गायी", attention: "लक्ष देणे आवश्यक", healthy: "आज निरोगी", offline: "ऑफलाइन मोड", online: "ऑनलाइन", high: "जास्त धोका", medium: "लक्षपूर्वक पाहा", low: "कमी धोका", activeAlert: "सक्रिय सूचना", recommendation: "सुचवलेली कृती", history: "धोक्याचा इतिहास", trendTitle: "बदल लवकर लक्षात आला", switchToVet: "पशुवैद्य दृश्यावर जा", switchToFarmer: "शेतकरी दृश्यावर परत", menu: "मेनू", activeAlerts: "सक्रिय सूचना", farmsFlagged: "या आठवड्यात धोक्यातील फार्म", casesMonth: "या महिन्यातील निश्चित प्रकरणे", animals: "निगराणीतील प्राणी", sortRisk: "धोक्यानुसार क्रम", allAlerts: "सर्व सूचना", highOnly: "फक्त जास्त धोका", noAction: "कृती आवश्यक नाही — नेहमीप्रमाणे लक्ष ठेवा.", earlyWarning: "लवकर इशारा", demoNote: "डेमो डेटा · हार्डवेअर जोडलेले नाही", aboutTitleLine1: "लवकर जाणून घ्या.", aboutTitleLine2: "चांगली काळजी घ्या.", aboutBody: "तुमच्या लक्षात येण्याच्या काही दिवस आधी आम्ही गायीच्या दुधातील संसर्गाची सुरुवातीची चिन्हे तपासतो.", howOneTitle: "दूध काढताना तपासा", howOneBody: "तुमच्या सकाळच्या दिनक्रमात छोटा सेन्सर प्रत्येक गाय वाचतो.", howTwoTitle: "बदलावर लक्ष ठेवा", howTwoBody: "आम्ही फक्त एक रीडिंग नाही तर कालांतराने नमुना पाहतो.", howThreeTitle: "लवकर कृती करा", howThreeBody: "स्पष्ट सूचना समस्या वाढण्यापूर्वी पशुवैद्याशी बोलण्यास मदत करते.", aboutNoteTitle: "खऱ्या शेतातील सकाळीसाठी बनवलेले.", aboutNoteBody: "मोठी बटणे, सोपे रंग, मराठी मदत आणि ऑफलाइन रीडिंग Pashu Mitra ला गोठ्यात उपयुक्त ठेवतात.", phaseTwo: "फेज २ रोडमॅप · सहकारी विस्तार", herdOverview: "कळपाच्या आरोग्याचा आढावा", herdOverviewBody: "सीता देवी डेअरी आणि जवळच्या फार्मची स्पष्ट माहिती.", priorityList: "प्राधान्य यादी", animalsToReview: "तपासायचे प्राणी", selectedAnimal: "निवडलेला प्राणी", tableAnimal: "प्राणी", tableFarm: "फार्म", tableRisk: "धोका", lastReading: "शेवटचे रीडिंग", tableAction: "कृती", reviewed: "तपासले", review: "तपासा", weekLabel: "आठवडा ३६ · २०२६", readingCompletion: "रीडिंग पूर्णता", cooperativeDesk: "सहकारी फील्ड डेस्क", needsFollowup: "फॉलो-अप आवश्यक", treatedEarly: "दोन्हीवर लवकर उपचार", acrossFarms: "८ फार्ममध्ये", confirm: "निश्चित करा", falseAlarmAction: "चुकीची सूचना", noAnimalsMatch: "कोणताही प्राणी जुळला नाही", riskChartNote: "१४ दिवसांचा धोका. वाढती रेषा वेळेवर शारीरिक तपासणीचा संकेत देते." },
  gu: { ...copy.en, home: "મારી ગાયો", alerts: "સૂચનાઓ", about: "આ કેવી રીતે કામ કરે છે", farmer: "ખેડૂત દૃશ્ય", vet: "પશુચિકિત્સક દૃશ્ય", greeting: "સુપ્રભાત, સીતા", subtitle: "આજે તમારા ટોળાનું સ્વાસ્થ્ય.", checkCows: "ગાયો તપાસો", checking: "રીડિંગ તપાસી રહ્યા છીએ…", monitored: "નિરીક્ષણમાં ગાયો", attention: "ધ્યાન જરૂરી", healthy: "આજે સ્વસ્થ", offline: "ઑફલાઇન મોડ", online: "ઑનલાઇન", high: "વધુ જોખમ", medium: "ધ્યાનથી જુઓ", low: "ઓછું જોખમ", activeAlert: "સક્રિય સૂચના", recommendation: "ભલામણ કરેલી કાર્યવાહી", history: "જોખમનો ઇતિહાસ", trendTitle: "ફેરફાર વહેલો જણાયો", switchToVet: "પશુચિકિત્સક દૃશ્ય પર જાઓ", switchToFarmer: "ખેડૂત દૃશ્ય પર પાછા", menu: "મેનૂ", activeAlerts: "સક્રિય સૂચનાઓ", farmsFlagged: "આ અઠવાડિયે જોખમવાળા ફાર્મ", casesMonth: "આ મહિનાના પુષ્ટિ થયેલા કેસ", animals: "નિરીક્ષણમાં પ્રાણીઓ", sortRisk: "જોખમ પ્રમાણે ગોઠવો", allAlerts: "બધી સૂચનાઓ", highOnly: "માત્ર વધુ જોખમ", noAction: "કોઈ કાર્યવાહી જરૂરી નથી — સામાન્ય દેખરેખ રાખો.", earlyWarning: "વહેલી ચેતવણી", demoNote: "ડેમો ડેટા · હાર્ડવેર જોડાયેલ નથી", aboutTitleLine1: "વહેલું જાણો.", aboutTitleLine2: "સારી સંભાળ રાખો.", aboutBody: "તમને કંઈ જણાય તે પહેલાંના દિવસોમાં અમે ગાયના દૂધમાં ચેપના પ્રારંભિક સંકેતો તપાસીએ છીએ.", howOneTitle: "દોહતી વખતે તપાસો", howOneBody: "નાનો સેન્સર તમારી સવારની દિનચર્યામાં દરેક ગાયને વાંચે છે.", howTwoTitle: "ફેરફાર પર નજર રાખો", howTwoBody: "અમે માત્ર એક રીડિંગ નહીં, સમય સાથેની પેટર્ન જોઈએ છીએ.", howThreeTitle: "વહેલી કાર્યવાહી કરો", howThreeBody: "સ્પષ્ટ સૂચના સમસ્યા વધે તે પહેલાં પશુચિકિત્સક સાથે વાત કરવામાં મદદ કરે છે.", aboutNoteTitle: "ખેતરની વાસ્તવિક સવાર માટે બનાવેલું.", aboutNoteBody: "મોટા બટન, સરળ રંગો, ગુજરાતી સહાય અને ઑફલાઇન રીડિંગ Pashu Mitra ને તબેલામાં ઉપયોગી રાખે છે.", phaseTwo: "ફેઝ ૨ રોડમેપ · સહકારી વિસ્તરણ", herdOverview: "ટોળાના સ્વાસ્થ્યનો સારાંશ", herdOverviewBody: "સીતા દેવી ડેરી અને નજીકના ફાર્મની સ્પષ્ટ માહિતી.", priorityList: "પ્રાથમિકતા યાદી", animalsToReview: "સમીક્ષા કરવાના પ્રાણીઓ", selectedAnimal: "પસંદ કરેલ પ્રાણી", tableAnimal: "પ્રાણી", tableFarm: "ફાર્મ", tableRisk: "જોખમ", lastReading: "છેલ્લું રીડિંગ", tableAction: "કાર્યવાહી", reviewed: "સમીક્ષા થઈ", review: "સમીક્ષા કરો", weekLabel: "અઠવાડિયું ૩૬ · ૨૦૨૬", readingCompletion: "રીડિંગ પૂર્ણતા", cooperativeDesk: "સહકારી ફીલ્ડ ડેસ્ક", needsFollowup: "ફોલો-અપ જરૂરી", treatedEarly: "બંનેની વહેલી સારવાર થઈ", acrossFarms: "૮ ફાર્મમાં", confirm: "પુષ્ટિ કરો", falseAlarmAction: "ખોટી સૂચના", noAnimalsMatch: "કોઈ પ્રાણી મળ્યું નથી", riskChartNote: "૧૪ દિવસનો જોખમ. વધતી રેખા સમયસર શારીરિક તપાસનો સંકેત આપે છે." },
  pa: { ...copy.en, home: "ਮੇਰੀਆਂ ਗਾਵਾਂ", alerts: "ਸੂਚਨਾਵਾਂ", about: "ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ", farmer: "ਕਿਸਾਨ ਦ੍ਰਿਸ਼", vet: "ਪਸ਼ੂ ਡਾਕਟਰ ਦ੍ਰਿਸ਼", greeting: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ, ਸੀਤਾ", subtitle: "ਅੱਜ ਤੁਹਾਡੇ ਝੁੰਡ ਦੀ ਸਿਹਤ.", checkCows: "ਗਾਵਾਂ ਦੀ ਜਾਂਚ ਕਰੋ", checking: "ਰੀਡਿੰਗ ਜਾਂਚ ਰਹੇ ਹਾਂ…", monitored: "ਨਿਗਰਾਨੀ ਹੇਠ ਗਾਵਾਂ", attention: "ਧਿਆਨ ਦੀ ਲੋੜ", healthy: "ਅੱਜ ਤੰਦਰੁਸਤ", offline: "ਆਫਲਾਈਨ ਮੋਡ", online: "ਆਨਲਾਈਨ", high: "ਵੱਧ ਖਤਰਾ", medium: "ਧਿਆਨ ਨਾਲ ਦੇਖੋ", low: "ਘੱਟ ਖਤਰਾ", activeAlert: "ਸਰਗਰਮ ਸੂਚਨਾ", recommendation: "ਸਿਫ਼ਾਰਸ਼ੀ ਕਾਰਵਾਈ", history: "ਖਤਰੇ ਦਾ ਇਤਿਹਾਸ", trendTitle: "ਬਦਲਾਅ ਜਲਦੀ ਪਤਾ ਲੱਗਾ", switchToVet: "ਪਸ਼ੂ ਡਾਕਟਰ ਦ੍ਰਿਸ਼ ਤੇ ਜਾਓ", switchToFarmer: "ਕਿਸਾਨ ਦ੍ਰਿਸ਼ ਤੇ ਵਾਪਸ", menu: "ਮੀਨੂ", activeAlerts: "ਸਰਗਰਮ ਸੂਚਨਾਵਾਂ", farmsFlagged: "ਇਸ ਹਫ਼ਤੇ ਖਤਰੇ ਵਾਲੇ ਫਾਰਮ", casesMonth: "ਇਸ ਮਹੀਨੇ ਪੁਸ਼ਟੀਸ਼ੁਦਾ ਕੇਸ", animals: "ਨਿਗਰਾਨੀ ਹੇਠ ਜਾਨਵਰ", sortRisk: "ਖਤਰੇ ਅਨੁਸਾਰ", allAlerts: "ਸਾਰੀਆਂ ਸੂਚਨਾਵਾਂ", highOnly: "ਸਿਰਫ਼ ਵੱਧ ਖਤਰਾ", noAction: "ਕੋਈ ਕਾਰਵਾਈ ਲੋੜੀਂਦੀ ਨਹੀਂ — ਆਮ ਨਿਗਰਾਨੀ ਰੱਖੋ.", earlyWarning: "ਜਲਦੀ ਚੇਤਾਵਨੀ", demoNote: "ਡੈਮੋ ਡਾਟਾ · ਹਾਰਡਵੇਅਰ ਜੁੜਿਆ ਨਹੀਂ", aboutTitleLine1: "ਜਲਦੀ ਜਾਣੋ.", aboutTitleLine2: "ਚੰਗੀ ਦੇਖਭਾਲ ਕਰੋ.", aboutBody: "ਤੁਹਾਨੂੰ ਪਤਾ ਲੱਗਣ ਤੋਂ ਕਈ ਦਿਨ ਪਹਿਲਾਂ ਅਸੀਂ ਗਾਂ ਦੇ ਦੁੱਧ ਵਿੱਚ ਇਨਫੈਕਸ਼ਨ ਦੇ ਸ਼ੁਰੂਆਤੀ ਸੰਕੇਤ ਜਾਂਚਦੇ ਹਾਂ.", howOneTitle: "ਦੁੱਧ ਕੱਢਦੇ ਸਮੇਂ ਜਾਂਚੋ", howOneBody: "ਛੋਟਾ ਸੈਂਸਰ ਤੁਹਾਡੀ ਸਵੇਰ ਦੀ ਰੁਟੀਨ ਵਿੱਚ ਹਰ ਗਾਂ ਨੂੰ ਪੜ੍ਹਦਾ ਹੈ.", howTwoTitle: "ਬਦਲਾਅ ਤੇ ਨਜ਼ਰ ਰੱਖੋ", howTwoBody: "ਅਸੀਂ ਸਿਰਫ਼ ਇੱਕ ਰੀਡਿੰਗ ਨਹੀਂ, ਸਮੇਂ ਨਾਲ ਪੈਟਰਨ ਵੇਖਦੇ ਹਾਂ.", howThreeTitle: "ਜਲਦੀ ਕਾਰਵਾਈ ਕਰੋ", howThreeBody: "ਸਪਸ਼ਟ ਸੂਚਨਾ ਸਮੱਸਿਆ ਵਧਣ ਤੋਂ ਪਹਿਲਾਂ ਪਸ਼ੂ ਡਾਕਟਰ ਨਾਲ ਗੱਲ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰਦੀ ਹੈ.", aboutNoteTitle: "ਅਸਲੀ ਖੇਤ ਦੀ ਸਵੇਰ ਲਈ ਬਣਾਇਆ ਗਿਆ.", aboutNoteBody: "ਵੱਡੇ ਬਟਨ, ਸਧਾਰਨ ਰੰਗ, ਪੰਜਾਬੀ ਸਹਾਇਤਾ ਅਤੇ ਆਫਲਾਈਨ ਰੀਡਿੰਗ Pashu Mitra ਨੂੰ ਪਸ਼ੂਆਂ ਦੇ ਥਾਂ ਤੇ ਲਾਭਦਾਇਕ ਰੱਖਦੇ ਹਨ.", phaseTwo: "ਫੇਜ਼ ੨ ਰੋਡਮੈਪ · ਸਹਿਕਾਰੀ ਵਿਸਥਾਰ", herdOverview: "ਝੁੰਡ ਦੀ ਸਿਹਤ ਦਾ ਜਾਇਜ਼ਾ", herdOverviewBody: "ਸੀਤਾ ਦੇਵੀ ਡੇਅਰੀ ਅਤੇ ਨੇੜਲੇ ਫਾਰਮਾਂ ਦੀ ਸਪਸ਼ਟ ਤਸਵੀਰ.", priorityList: "ਤਰਜੀਹ ਸੂਚੀ", animalsToReview: "ਜਿਨ੍ਹਾਂ ਜਾਨਵਰਾਂ ਦੀ ਸਮੀਖਿਆ ਕਰਨੀ ਹੈ", selectedAnimal: "ਚੁਣਿਆ ਜਾਨਵਰ", tableAnimal: "ਜਾਨਵਰ", tableFarm: "ਫਾਰਮ", tableRisk: "ਖਤਰਾ", lastReading: "ਆਖਰੀ ਰੀਡਿੰਗ", tableAction: "ਕਾਰਵਾਈ", reviewed: "ਸਮੀਖਿਆ ਹੋਈ", review: "ਸਮੀਖਿਆ ਕਰੋ", weekLabel: "ਹਫ਼ਤਾ ੩੬ · ੨੦੨੬", readingCompletion: "ਰੀਡਿੰਗ ਪੂਰਨਤਾ", cooperativeDesk: "ਸਹਿਕਾਰੀ ਫੀਲਡ ਡੈਸਕ", needsFollowup: "ਫਾਲੋ-ਅੱਪ ਲੋੜੀਂਦਾ", treatedEarly: "ਦੋਵਾਂ ਦਾ ਜਲਦੀ ਇਲਾਜ ਹੋਇਆ", acrossFarms: "੮ ਫਾਰਮਾਂ ਵਿੱਚ", confirm: "ਪੁਸ਼ਟੀ ਕਰੋ", falseAlarmAction: "ਗਲਤ ਸੂਚਨਾ", noAnimalsMatch: "ਕੋਈ ਜਾਨਵਰ ਨਹੀਂ ਮਿਲਿਆ", riskChartNote: "੧੪ ਦਿਨਾਂ ਦਾ ਖਤਰਾ. ਵਧਦੀ ਲਾਈਨ ਸਮੇਂ ਸਿਰ ਜਾਂਚ ਦਾ ਸੰਕੇਤ ਦਿੰਦੀ ਹੈ." },
  kn: { ...copy.en, home: "ನನ್ನ ಹಸುಗಳು", alerts: "ಎಚ್ಚರಿಕೆಗಳು", about: "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ", farmer: "ರೈತ ವೀಕ್ಷಣೆ", vet: "ಪಶುವೈದ್ಯ ವೀಕ್ಷಣೆ", greeting: "ಶುಭೋದಯ, ಸೀತಾ", subtitle: "ಇಂದು ನಿಮ್ಮ ಹಿಂಡಿನ ಆರೋಗ್ಯ.", checkCows: "ಹಸುಗಳನ್ನು ಪರೀಕ್ಷಿಸಿ", checking: "ರೀಡಿಂಗ್ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ…", monitored: "ಮೇಲ್ವಿಚಾರಣೆಯಲ್ಲಿರುವ ಹಸುಗಳು", attention: "ಗಮನ ಅಗತ್ಯ", healthy: "ಇಂದು ಆರೋಗ್ಯಕರ", offline: "ಆಫ್‌ಲೈನ್ ಮೋಡ್", online: "ಆನ್‌ಲೈನ್", high: "ಹೆಚ್ಚಿನ ಅಪಾಯ", medium: "ಎಚ್ಚರಿಕೆಯಿಂದ ನೋಡಿ", low: "ಕಡಿಮೆ ಅಪಾಯ", activeAlert: "ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆ", recommendation: "ಶಿಫಾರಸು ಮಾಡಿದ ಕ್ರಮ", history: "ಅಪಾಯದ ಇತಿಹಾಸ", trendTitle: "ಬದಲಾವಣೆ ಬೇಗ ಕಂಡುಬಂದಿತು", switchToVet: "ಪಶುವೈದ್ಯ ವೀಕ್ಷಣೆಗೆ ಬದಲಿಸಿ", switchToFarmer: "ರೈತ ವೀಕ್ಷಣೆಗೆ ಹಿಂತಿರುಗಿ", menu: "ಮೆನು", activeAlerts: "ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳು", farmsFlagged: "ಈ ವಾರ ಗುರುತಿಸಲಾದ ಫಾರ್ಮ್‌ಗಳು", casesMonth: "ಈ ತಿಂಗಳ ದೃಢಪಟ್ಟ ಪ್ರಕರಣಗಳು", animals: "ಮೇಲ್ವಿಚಾರಣೆಯಲ್ಲಿರುವ ಪ್ರಾಣಿಗಳು", sortRisk: "ಅಪಾಯದ ಪ್ರಕಾರ", allAlerts: "ಎಲ್ಲಾ ಎಚ್ಚರಿಕೆಗಳು", highOnly: "ಹೆಚ್ಚಿನ ಅಪಾಯ ಮಾತ್ರ", noAction: "ಯಾವುದೇ ಕ್ರಮ ಅಗತ್ಯವಿಲ್ಲ — ಎಂದಿನಂತೆ ಗಮನಿಸಿ.", earlyWarning: "ಮುಂಚಿನ ಎಚ್ಚರಿಕೆ", demoNote: "ಡೆಮೋ ಡೇಟಾ · ಹಾರ್ಡ್‌ವೇರ್ ಸಂಪರ್ಕಗೊಂಡಿಲ್ಲ", aboutTitleLine1: "ಬೇಗ ತಿಳಿಯಿರಿ.", aboutTitleLine2: "ಉತ್ತಮ ಆರೈಕೆ ಮಾಡಿ.", aboutBody: "ನಿಮಗೆ ಕಾಣಿಸುವ ಹಲವು ದಿನಗಳ ಮುಂಚೆಯೇ ಹಸುವಿನ ಹಾಲಿನಲ್ಲಿ ಸೋಂಕಿನ ಆರಂಭಿಕ ಲಕ್ಷಣಗಳನ್ನು ನಾವು ಪರಿಶೀಲಿಸುತ್ತೇವೆ.", howOneTitle: "ಹಾಲು ಕರೆಯುವಾಗ ಪರಿಶೀಲಿಸಿ", howOneBody: "ನಿಮ್ಮ ಬೆಳಗಿನ ದಿನಚರಿಯಲ್ಲೇ ಸಣ್ಣ ಸೆನ್ಸರ್ ಪ್ರತಿ ಹಸುವನ್ನು ಓದುತ್ತದೆ.", howTwoTitle: "ಬದಲಾವಣೆಯನ್ನು ಗಮನಿಸಿ", howTwoBody: "ನಾವು ಒಂದೇ ರೀಡಿಂಗ್ ಅಲ್ಲ, ಕಾಲಕ್ರಮೇಣದ ಮಾದರಿಯನ್ನು ನೋಡುತ್ತೇವೆ.", howThreeTitle: "ಬೇಗ ಕ್ರಮ ಕೈಗೊಳ್ಳಿ", howThreeBody: "ಸ್ಪಷ್ಟ ಎಚ್ಚರಿಕೆಯು ಸಮಸ್ಯೆ ಹೆಚ್ಚಾಗುವ ಮುನ್ನ ಪಶುವೈದ್ಯರೊಂದಿಗೆ ಮಾತನಾಡಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.", aboutNoteTitle: "ನಿಜವಾದ ಕೃಷಿ ಬೆಳಗ್ಗಿಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ.", aboutNoteBody: "ದೊಡ್ಡ ಬಟನ್‌ಗಳು, ಸರಳ ಬಣ್ಣಗಳು, ಕನ್ನಡ ಬೆಂಬಲ ಮತ್ತು ಆಫ್‌ಲೈನ್ ರೀಡಿಂಗ್ Pashu Mitra ಅನ್ನು ಕೊಟ್ಟಿಗೆಯಲ್ಲೂ ಉಪಯುಕ್ತವಾಗಿಸುತ್ತವೆ.", phaseTwo: "ಹಂತ ೨ ರೋಡ್‌ಮ್ಯಾಪ್ · ಸಹಕಾರಿ ವಿಸ್ತರಣೆ", herdOverview: "ಹಿಂಡಿನ ಆರೋಗ್ಯದ ಅವಲೋಕನ", herdOverviewBody: "ಸೀತಾ ದೇವಿ ಡೈರಿ ಮತ್ತು ಹತ್ತಿರದ ಫಾರ್ಮ್‌ಗಳ ಸ್ಪಷ್ಟ ಚಿತ್ರ.", priorityList: "ಆದ್ಯತಾ ಪಟ್ಟಿ", animalsToReview: "ಪರಿಶೀಲಿಸಬೇಕಾದ ಪ್ರಾಣಿಗಳು", selectedAnimal: "ಆಯ್ಕೆ ಮಾಡಿದ ಪ್ರಾಣಿ", tableAnimal: "ಪ್ರಾಣಿ", tableFarm: "ಫಾರ್ಮ್", tableRisk: "ಅಪಾಯ", lastReading: "ಕೊನೆಯ ರೀಡಿಂಗ್", tableAction: "ಕ್ರಮ", reviewed: "ಪರಿಶೀಲಿಸಲಾಗಿದೆ", review: "ಪರಿಶೀಲಿಸಿ", weekLabel: "ವಾರ ೩೬ · ೨೦೨೬", readingCompletion: "ರೀಡಿಂಗ್ ಪೂರ್ಣತೆ", cooperativeDesk: "ಸಹಕಾರಿ ಫೀಲ್ಡ್ ಡೆಸ್ಕ್", needsFollowup: "ಫಾಲೋ-ಅಪ್ ಅಗತ್ಯ", treatedEarly: "ಎರಡಕ್ಕೂ ಬೇಗ ಚಿಕಿತ್ಸೆ", acrossFarms: "೮ ಫಾರ್ಮ್‌ಗಳಲ್ಲಿ", confirm: "ದೃಢೀಕರಿಸಿ", falseAlarmAction: "ಸುಳ್ಳು ಎಚ್ಚರಿಕೆ", noAnimalsMatch: "ಯಾವುದೇ ಪ್ರಾಣಿ ಹೊಂದಿಕೆಯಾಗಲಿಲ್ಲ", riskChartNote: "೧೪ ದಿನಗಳ ಅಪಾಯ. ಏರುತ್ತಿರುವ ರೇಖೆಯು ಸಮಯೋಚಿತ ದೈಹಿಕ ಪರೀಕ್ಷೆಯ ಸೂಚನೆ." },
  ta: { ...copy.en, home: "என் மாடுகள்", alerts: "எச்சரிக்கைகள்", about: "இது எப்படி செயல்படுகிறது", farmer: "விவசாயி பார்வை", vet: "கால்நடை மருத்துவர் பார்வை", greeting: "காலை வணக்கம், சீதா", subtitle: "இன்று உங்கள் மந்தையின் ஆரோக்கியம்.", checkCows: "மாடுகளைச் சரிபார்க்கவும்", checking: "வாசிப்புகளைச் சரிபார்க்கிறது…", monitored: "கண்காணிப்பில் உள்ள மாடுகள்", attention: "கவனம் தேவை", healthy: "இன்று ஆரோக்கியம்", offline: "ஆஃப்லைன் முறை", online: "ஆன்லைன்", high: "அதிக ஆபத்து", medium: "கவனமாகக் கண்காணிக்கவும்", low: "குறைந்த ஆபத்து", activeAlert: "செயலில் உள்ள எச்சரிக்கை", recommendation: "பரிந்துரைக்கப்பட்ட செயல்", history: "ஆபத்து வரலாறு", trendTitle: "மாற்றத்தை முன்கூட்டியே கண்டோம்", switchToVet: "மருத்துவர் பார்வைக்கு மாறவும்", switchToFarmer: "விவசாயி பார்வைக்குத் திரும்பவும்", menu: "மெனு", activeAlerts: "செயலில் உள்ள எச்சரிக்கைகள்", farmsFlagged: "இந்த வாரம் குறிக்கப்பட்ட பண்ணைகள்", casesMonth: "இந்த மாதம் உறுதி செய்யப்பட்ட வழக்குகள்", animals: "கண்காணிக்கப்படும் விலங்குகள்", sortRisk: "ஆபத்தின் படி வரிசை", allAlerts: "அனைத்து எச்சரிக்கைகள்", highOnly: "அதிக ஆபத்து மட்டும்", noAction: "செயல் தேவையில்லை — வழக்கம்போல் கண்காணிக்கவும்.", earlyWarning: "முன்கூட்டிய எச்சரிக்கை", demoNote: "டெமோ தரவு · வன்பொருள் இணைக்கப்படவில்லை", aboutTitleLine1: "முன்கூட்டியே அறியுங்கள்.", aboutTitleLine2: "சிறந்த பராமரிப்பு செய்யுங்கள்.", aboutBody: "உங்களுக்கு அறிகுறிகள் தெரிவதற்கு பல நாட்களுக்கு முன்பே, உங்கள் மாட்டுப் பாலில் தொற்றின் ஆரம்ப அறிகுறிகளை நாங்கள் சரிபார்க்கிறோம்.", howOneTitle: "பால் கறக்கும் போது சரிபார்க்கவும்", howOneBody: "உங்கள் காலை வழக்கத்திலேயே சிறிய சென்சார் ஒவ்வொரு மாட்டையும் படிக்கும்.", howTwoTitle: "மாற்றத்தைக் கவனியுங்கள்", howTwoBody: "ஒரு வாசிப்பு மட்டுமல்ல, காலப்போக்கில் உள்ள முறையைப் பார்க்கிறோம்.", howThreeTitle: "முன்கூட்டியே செயல்படுங்கள்", howThreeBody: "தெளிவான எச்சரிக்கை பிரச்சினை பெரிதாகும் முன் மருத்துவரிடம் பேச உதவும்.", aboutNoteTitle: "உண்மையான பண்ணை காலைக்காக உருவாக்கப்பட்டது.", aboutNoteBody: "பெரிய பொத்தான்கள், எளிய வண்ணங்கள், தமிழ் ஆதரவு மற்றும் ஆஃப்லைன் வாசிப்புகள் Pashu Mitra-வை மாட்டுத் தொழுவத்திலும் பயனுள்ளதாக வைத்திருக்கின்றன.", phaseTwo: "கட்டம் ௨ சாலைவரைபடம் · கூட்டுறவு விரிவாக்கம்", herdOverview: "மந்தை ஆரோக்கிய மேலோட்டம்", herdOverviewBody: "சீதா தேவி பால் பண்ணை மற்றும் அருகிலுள்ள பண்ணைகளின் தெளிவான படம்.", priorityList: "முன்னுரிமைப் பட்டியல்", animalsToReview: "மதிப்பாய்வு செய்ய வேண்டிய விலங்குகள்", selectedAnimal: "தேர்ந்தெடுக்கப்பட்ட விலங்கு", tableAnimal: "விலங்கு", tableFarm: "பண்ணை", tableRisk: "ஆபத்து", lastReading: "கடைசி வாசிப்பு", tableAction: "செயல்", reviewed: "மதிப்பாய்வு செய்யப்பட்டது", review: "மதிப்பாய்வு செய்க", weekLabel: "வாரம் ௩௬ · ௨௦௨௨", readingCompletion: "வாசிப்பு நிறைவு", cooperativeDesk: "கூட்டுறவு கள மேசை", needsFollowup: "தொடர் நடவடிக்கை தேவை", treatedEarly: "இரண்டுக்கும் முன்கூட்டியே சிகிச்சை", acrossFarms: "௮ பண்ணைகளில்", confirm: "உறுதிப்படுத்துக", falseAlarmAction: "தவறான எச்சரிக்கை", noAnimalsMatch: "விலங்குகள் பொருந்தவில்லை", riskChartNote: "௧௪ நாள் ஆபத்து. உயரும் கோடு சரியான நேரத்தில் உடல் பரிசோதனையைச் சுட்டுகிறது." },
  te: { ...copy.en, home: "నా ఆవులు", alerts: "హెచ్చరికలు", about: "ఇది ఎలా పనిచేస్తుంది", farmer: "రైతు వీక్షణ", vet: "పశువైద్య వీక్షణ", greeting: "శుభోదయం, సీత", subtitle: "ఈ రోజు మీ మంద ఆరోగ్యం.", checkCows: "ఆవులను తనిఖీ చేయండి", checking: "రీడింగ్‌లను తనిఖీ చేస్తున్నాం…", monitored: "పర్యవేక్షణలోని ఆవులు", attention: "శ్రద్ధ అవసరం", healthy: "ఈ రోజు ఆరోగ్యంగా", offline: "ఆఫ్‌లైన్ మోడ్", online: "ఆన్‌లైన్", high: "అధిక ప్రమాదం", medium: "జాగ్రత్తగా చూడండి", low: "తక్కువ ప్రమాదం", activeAlert: "క్రియాశీల హెచ్చరిక", recommendation: "సిఫార్సు చేసిన చర్య", history: "ప్రమాద చరిత్ర", trendTitle: "మార్పును ముందుగానే గుర్తించాం", switchToVet: "పశువైద్య వీక్షణకు మారండి", switchToFarmer: "రైతు వీక్షణకు తిరిగి వెళ్లండి", menu: "మెను", activeAlerts: "క్రియాశీల హెచ్చరికలు", farmsFlagged: "ఈ వారం గుర్తించిన ఫారాలు", casesMonth: "ఈ నెల నిర్ధారించిన కేసులు", animals: "పర్యవేక్షణలోని జంతువులు", sortRisk: "ప్రమాదం ప్రకారం", allAlerts: "అన్ని హెచ్చరికలు", highOnly: "అధిక ప్రమాదం మాత్రమే", noAction: "చర్య అవసరం లేదు — సాధారణంగా పర్యవేక్షించండి.", earlyWarning: "ముందస్తు హెచ్చరిక", demoNote: "డెమో డేటా · హార్డ్‌వేర్ కనెక్ట్ కాలేదు", aboutTitleLine1: "ముందుగానే తెలుసుకోండి.", aboutTitleLine2: "మెరుగైన సంరక్షణ చేయండి.", aboutBody: "మీకు కనిపించే లక్షణాలకు కొన్ని రోజుల ముందే, మీ ఆవు పాలలో సంక్రమణ ప్రారంభ సంకేతాలను మేము తనిఖీ చేస్తాము.", howOneTitle: "పాలు పితికేటప్పుడు తనిఖీ చేయండి", howOneBody: "మీ ఉదయపు దినచర్యలోనే చిన్న సెన్సార్ ప్రతి ఆవును చదువుతుంది.", howTwoTitle: "మార్పును గమనించండి", howTwoBody: "ఒక్క రీడింగ్ కాకుండా కాలక్రమంలోని నమూనాను చూస్తాము.", howThreeTitle: "ముందుగానే చర్య తీసుకోండి", howThreeBody: "స్పష్టమైన హెచ్చరిక సమస్య పెరగకముందే పశువైద్యుడితో మాట్లాడటానికి సహాయపడుతుంది.", aboutNoteTitle: "నిజమైన వ్యవసాయ ఉదయాల కోసం నిర్మించబడింది.", aboutNoteBody: "పెద్ద బటన్లు, సరళమైన రంగులు, తెలుగు మద్దతు మరియు ఆఫ్‌లైన్ రీడింగ్‌లు Pashu Mitraని పశువుల కొట్టంలో ఉపయోగకరంగా ఉంచుతాయి.", phaseTwo: "దశ ౨ రోడ్‌మ్యాప్ · సహకార విస్తరణ", herdOverview: "మంద ఆరోగ్య అవలోకనం", herdOverviewBody: "సీతా దేవి డైరీ మరియు సమీప ఫారాల స్పష్టమైన చిత్రం.", priorityList: "ప్రాధాన్యత జాబితా", animalsToReview: "సమీక్షించాల్సిన జంతువులు", selectedAnimal: "ఎంచుకున్న జంతువు", tableAnimal: "జంతువు", tableFarm: "ఫారం", tableRisk: "ప్రమాదం", lastReading: "చివరి రీడింగ్", tableAction: "చర్య", reviewed: "సమీక్షించబడింది", review: "సమీక్షించండి", weekLabel: "వారం ౩౬ · ౨౦౨౬", readingCompletion: "రీడింగ్ పూర్తి", cooperativeDesk: "సహకార ఫీల్డ్ డెస్క్", needsFollowup: "ఫాలో-అప్ అవసరం", treatedEarly: "రెండింటికీ ముందుగానే చికిత్స", acrossFarms: "౮ ఫారాల్లో", confirm: "నిర్ధారించండి", falseAlarmAction: "తప్పుడు హెచ్చరిక", noAnimalsMatch: "జంతువులు సరిపోలలేదు", riskChartNote: "౧౪ రోజుల ప్రమాదం. పెరుగుతున్న రేఖ సమయానుకూల శారీరక పరీక్షకు సంకేతం." },
};

export type ExtraCopy = {
  weatherToday: string; weatherLocationLabel: string; farmerProfile: string; profileSubtitle: string; farmerLabel: string; phoneLabel: string; villageLabel: string; memberSinceLabel: string; dairyLabel: string; registeredDevices: string; cowsRegistered: string; sensorDevices: string; currentPreference: string; languageHelp: string; changeLanguage: string; localVet: string; largeAnimalSpecialist: string; availableToday: string; shareReading: string; startDemoCall: string; demoInteraction: string; sensorConnected: string; sensorLow: string; sensorStale: string; liveDemoFeed: string; callingVet: string; queuedReadings: string; syncedReadings: string; backOnline: string; offlineOn: string; vetConfirmedToast: string; falseAlarmToast: string; farmerOverview: string; farmTitle: string; farmSubtitle: string; cowsRegisteredStat: string; currentHerd: string; sensorsConnected: string; sensorsNotResponding: string; lowBattery: string; watchSensors: string; herdTrend: string; averageRisk: string; recentCare: string; lastResolved: string; noResolved: string; dayAgo: string; daysAgo: string; basedOnAlerts: string; sensorWatch: string; sensorNotRespondingPlural: string; dueChecks: string; dueChecksBody: string; allChecked: string; thisWeek: string; readingsTaken: string; alertsRaised: string; alertsResolved: string; advisory: string; advisoryHigh: string; advisoryMedium: string; advisoryGood: string; quickAccess: string; openAlerts: string; contactVet: string; useStatePicker: string; searchAnimals: string; close: string; actualFeed: string; modelRisk: string; modelRiskBody: string; riskScoreToday: string; infectionProbability: string; days: string; continuousHistory: string; routineTitle: string; routineBody: string; alertSubtitle: string; farmTrendNote: string; demoDerived: string; checkNow: string; noAnimals: string; vetValidationNote: string; dateToday: string;
  selectStateLabel: string; cooperativeOverview: string; perFarmRiskDist: string; weeklyAlertTrend: string; sevenDayTrajectory: string; hassanCoopDesk: string; registeredFarms: string; activeAnimals: string; telemetrySyncRate: string; subclinicalFlags: string; highRisk: string; medRisk: string; allLowRisk: string; normalRisk: string; weeklyTrendChange: string; explainableAi: string; featureTransparencyPanel: string; transparencyIntro: string; conductivityFeatureName: string; conductivityFeatureRole: string; conductivityFeatureDesc: string; temperatureFeatureName: string; temperatureFeatureRole: string; temperatureFeatureDesc: string; vetFeedbackNote: string; impactTechnologyRoadmap: string; subclinicalIntelligenceEconomicProtection: string; pitchIntro: string; card1Badge: string; card1Title: string; card1Body: string; card1Bullet1: string; card1Bullet2: string; card1Bullet3: string; card2Badge: string; card2Title: string; card2Body: string; card2Bullet1: string; card2Bullet2: string; card2Bullet3: string; card3Badge: string; card3Title: string; card3Body: string; card3Bullet1: string; card3Bullet2: string; card3Bullet3: string;
}
export const extraCopy: Record<Language, Partial<ExtraCopy>> = {
  en: { weatherToday: "Sunday, 6 September 2026", weatherLocationLabel: "Hassan, Karnataka", farmerProfile: "Farmer profile", profileSubtitle: "Your farmer identity and dairy details.", farmerLabel: "Farmer", phoneLabel: "Phone", villageLabel: "Village", memberSinceLabel: "Member since", dairyLabel: "Your dairy", registeredDevices: "Registered devices", cowsRegistered: "Cows registered", sensorDevices: "Sensor devices", currentPreference: "Current preference", languageHelp: "Your state picker controls the language across the app.", changeLanguage: "Change state / language", localVet: "Your local veterinarian", largeAnimalSpecialist: "Large animal specialist", availableToday: "Available today · 8 AM – 7 PM", shareReading: "Share the reading when you speak with the vet.", startDemoCall: "Start demo call", demoInteraction: "Demo interaction · no real call will be placed", sensorConnected: "Sensor connected", sensorLow: "Battery low", sensorStale: "Sensor not responding", liveDemoFeed: "Live demo feed", callingVet: "Calling Dr. Meera Rao… (demo)", queuedReadings: "readings queued · will sync when back online", syncedReadings: "queued readings synced · herd is up to date", backOnline: "Back online", offlineOn: "Offline mode on · readings stay on this device", vetConfirmedToast: "Vet confirmation recorded", falseAlarmToast: "Marked as a false alarm", farmerOverview: "Farmer overview", farmTitle: "My Farm", farmSubtitle: "A simple picture of your herd today.", cowsRegisteredStat: "Cows registered", currentHerd: "Your current herd", sensorsConnected: "Sensors connected", sensorsNotResponding: "not responding", lowBattery: "Low battery", watchSensors: "Watch these sensors", herdTrend: "Herd trend", averageRisk: "Average risk score", recentCare: "Recent care", lastResolved: "Last resolved alert", noResolved: "No resolved case yet", dayAgo: "day ago", daysAgo: "days ago", basedOnAlerts: "Based on the most recent confirmed or resolved alert in this demo.", sensorWatch: "Sensor watch", sensorNotRespondingPlural: "sensor(s) not responding.", dueChecks: "Cows due for a check", dueChecksBody: "These cows have not been checked today.", allChecked: "Every cow has a current reading today.", thisWeek: "This week", readingsTaken: "Readings taken", alertsRaised: "Alerts raised", alertsResolved: "Alerts resolved", advisory: "Today’s advisory", advisoryHigh: "needs attention today.", advisoryMedium: "could use a closer look today.", advisoryGood: "Your herd looks good — no cows need attention right now.", quickAccess: "Quick access", openAlerts: "Open alerts", contactVet: "Contact vet", useStatePicker: "Use the state picker above to change your language", searchAnimals: "Search animals…", close: "Close", actualFeed: "Today’s milk check", modelRisk: "AI risk model", modelRiskBody: "Trained on real conductivity and temperature data. This is not a diagnosis — it helps you speak to your vet at the right time.", riskScoreToday: "Today’s risk score", infectionProbability: "Probability of infection risk", days: "days", continuousHistory: "Continuous history", routineTitle: "Keep the good habit", routineBody: "One morning reading a day keeps your herd story clear.", alertSubtitle: "Every alert gives you one clear next step.", farmTrendNote: "Lower scores are generally calmer. This is an overview of your existing cow readings.", demoDerived: "Demo-derived summary · updates with current readings", checkNow: "Check now", noAnimals: "No animals match", vetValidationNote: "Vet-in-the-loop validation improves the next reading.", dateToday: "Sunday, 6 September 2026", selectStateLabel: "Select your state", cooperativeOverview: "Cooperative Overview", perFarmRiskDist: "Per-Farm Risk Distribution", weeklyAlertTrend: "Weekly Alert Trend", sevenDayTrajectory: "7-Day Trajectory", hassanCoopDesk: "Hassan District Dairy Union · Route 4 Cooperative Desk", registeredFarms: "Registered Farms", activeAnimals: "Active Animals", telemetrySyncRate: "Telemetry Sync Rate", subclinicalFlags: "Subclinical Flags", highRisk: "High Risk", medRisk: "Med Risk", allLowRisk: "All Low Risk", normalRisk: "Normal", weeklyTrendChange: "-28% vs Last Week", explainableAi: "Explainable AI", featureTransparencyPanel: "Feature Transparency Panel", transparencyIntro: "Subclinical risk predictions are generated by a neural network model trained on real conductivity and temperature telemetry from public datasets. Both inputs work together to estimate risk.", conductivityFeatureName: "Milk_Conductivity", conductivityFeatureRole: "Primary Sensor Signal · Direct Measure", conductivityFeatureDesc: "Measures Na⁺ and Cl⁻ ion concentration shifts in milk. Elevated electrical conductivity directly signals subclinical cell membrane permeability changes.", temperatureFeatureName: "Milk_Temperature", temperatureFeatureRole: "Secondary Sensor Signal · Co-factor", temperatureFeatureDesc: "Captures thermal variances. Combined with conductivity in the neural network, temperature helps distinguish early physiological shifts from ambient fluctuations.", vetFeedbackNote: "Model Validation: Real conductivity and temperature telemetry feed the 2-feature neural network. Clinical feedback (Confirmed / False Alarm) reinforces regional threshold accuracy.", impactTechnologyRoadmap: "Impact & Technology Roadmap", subclinicalIntelligenceEconomicProtection: "Subclinical Intelligence & Economic Protection", pitchIntro: "Pashu Mitra bridges advanced bio-sensing telemetry with rural dairy economics to eliminate silent production loss.", card1Badge: "2–4 Days Advance", card1Title: "Early Forecasting vs. Clinical Detection", card1Body: "Traditional clinical detection relies on visible symptoms after tissue damage occurs. Pashu Mitra tracks subclinical ion shifts and micro-thermal variances 2–4 days before physical manifestations appear.", card1Bullet1: "Detects ionic concentration shifts prior to cellular inflammation", card1Bullet2: "Enables early herbal/non-antibiotic supportive treatment", card1Bullet3: "Prevents permanent quarter tissue scarring and yield loss", card2Badge: "Smallholder Protection", card2Title: "Indian Dairy Economics & AMR Mitigation", card2Body: "Over 80% of India’s milk comes from smallholders owning 2–5 cows. Early triage protects household incomes and stops routine over-prescription of antibiotics that drives Antimicrobial Resistance (AMR).", card2Bullet1: "Saves ₹6k–₹10k per cow in treatment cost & dumped milk", card2Bullet2: "Prevents indiscriminate antibiotic overuse at the farm gate", card2Bullet3: "Safeguards cooperative milk union fat & SNF testing standards", card3Badge: "Phase 2 Roadmap", card3Title: "Hardware Prototype & Edge ML Deployment", card3Body: "Currently operating as a browser-validated predictive prototype with calibrated sensor inputs. Phase 2 transitions this logic directly onto handheld microcontrollers and stall-cup sensors for zero-connectivity rural dairies.", card3Bullet1: "Handheld IP67 EC dip probes & automated stall cup sensors", card3Bullet2: "Microcontroller edge TinyML inference without internet", card3Bullet3: "Seamless sync with Village Dairy Cooperative Society (VDCS)" },
  hi: { weatherToday: "रविवार, 6 सितंबर 2026", weatherLocationLabel: "हसन, कर्नाटक", farmerProfile: "किसान प्रोफ़ाइल", profileSubtitle: "आपकी किसान पहचान और डेयरी का विवरण।", farmerLabel: "किसान", phoneLabel: "फ़ोन", villageLabel: "गांव", memberSinceLabel: "सदस्य बने", dairyLabel: "आपकी डेयरी", registeredDevices: "पंजीकृत उपकरण", cowsRegistered: "पंजीकृत गायें", sensorDevices: "सेंसर उपकरण", currentPreference: "वर्तमान पसंद", languageHelp: "स्टेट पिकर पूरे ऐप की भाषा बदलता है।", changeLanguage: "राज्य / भाषा बदलें", localVet: "आपके क्षेत्र के डॉक्टर", largeAnimalSpecialist: "बड़े पशुओं के विशेषज्ञ", availableToday: "आज उपलब्ध · सुबह 8 – शाम 7 बजे", shareReading: "डॉक्टर से बात करते समय रीडिंग दिखाएं।", startDemoCall: "डेमो कॉल शुरू करें", demoInteraction: "डेमो इंटरैक्शन · असली कॉल नहीं होगी", sensorConnected: "सेंसर जुड़ा है", sensorLow: "बैटरी कम", sensorStale: "सेंसर जवाब नहीं दे रहा", liveDemoFeed: "लाइव डेमो फीड", callingVet: "डॉ. मीरा राव को कॉल किया जा रहा है… (डेमो)", queuedReadings: "रीडिंग कतार में हैं — ऑनलाइन होने पर सिंक होंगी", syncedReadings: "रीडिंग सिंक हो गईं — झुंड अपडेट है", backOnline: "फिर से ऑनलाइन", offlineOn: "ऑफलाइन मोड चालू · रीडिंग इसी डिवाइस पर रहेंगी", vetConfirmedToast: "डॉक्टर की पुष्टि दर्ज हुई", falseAlarmToast: "गलत चेतावनी दर्ज हुई", farmerOverview: "किसान अवलोकन", farmTitle: "मेरा फार्म", farmSubtitle: "आज आपके झुंड की सरल तस्वीर।", cowsRegisteredStat: "पंजीकृत गायें", currentHerd: "आपका मौजूदा झुंड", sensorsConnected: "जुड़े सेंसर", sensorsNotResponding: "जवाब नहीं दे रहे", lowBattery: "बैटरी कम", watchSensors: "इन सेंसर पर ध्यान दें", herdTrend: "झुंड का रुझान", averageRisk: "औसत जोखिम स्कोर", recentCare: "हाल की देखभाल", lastResolved: "अंतिम सुलझी सूचना", noResolved: "अभी कोई मामला सुलझा नहीं", dayAgo: "दिन पहले", daysAgo: "दिन पहले", basedOnAlerts: "इस डेमो में सबसे हाल की पुष्टि या सुलझी सूचना पर आधारित।", sensorWatch: "सेंसर पर ध्यान", sensorNotRespondingPlural: "सेंसर जवाब नहीं दे रहे।", dueChecks: "जिन गायों की जांच बाकी है", dueChecksBody: "इन गायों की आज जांच नहीं हुई।", allChecked: "आज हर गाय की ताज़ा रीडिंग है।", thisWeek: "इस सप्ताह", readingsTaken: "ली गई रीडिंग", alertsRaised: "उठी सूचनाएं", alertsResolved: "सुलझी सूचनाएं", advisory: "आज की सलाह", advisoryHigh: "को आज ध्यान चाहिए।", advisoryMedium: "पर आज थोड़ा और ध्यान दें।", advisoryGood: "आपका झुंड अच्छा है — अभी किसी गाय को ध्यान की जरूरत नहीं।", quickAccess: "त्वरित पहुंच", openAlerts: "सूचनाएं खोलें", contactVet: "डॉक्टर से संपर्क", useStatePicker: "भाषा बदलने के लिए ऊपर का स्टेट पिकर इस्तेमाल करें", searchAnimals: "पशु खोजें…", close: "बंद करें", actualFeed: "आज की दूध जांच", modelRisk: "AI जोखिम मॉडल", modelRiskBody: "वास्तविक चालकता और तापमान डेटा पर प्रशिक्षित। यह निदान नहीं है — समय पर डॉक्टर से बात करने में मदद करता है।", riskScoreToday: "आज का जोखिम स्कोर", infectionProbability: "संक्रमण जोखिम की संभावना", days: "दिन", continuousHistory: "लगातार निगरानी", routineTitle: "अच्छी आदत जारी रखें", routineBody: "दिन में एक बार सुबह की रीडिंग आपके झुंड की कहानी साफ रखती है।", alertSubtitle: "हर सूचना आपको अगला सही कदम बताती है।", farmTrendNote: "कम स्कोर आमतौर पर शांत स्थिति दिखाते हैं। यह आपकी मौजूदा रीडिंग का सार है।", demoDerived: "डेमो से निकला सार · मौजूदा रीडिंग के साथ बदलता है", checkNow: "अभी जांचें", noAnimals: "कोई पशु मेल नहीं खाता", vetValidationNote: "डॉक्टर की पुष्टि अगली रीडिंग बेहतर बनाती है।", dateToday: "रविवार, 6 सितंबर 2026", selectStateLabel: "अपना राज्य चुनें", cooperativeOverview: "सहकारी अवलोकन", perFarmRiskDist: "प्रति-फार्म जोखिम वितरण", weeklyAlertTrend: "साप्ताहिक अलर्ट रुझान", sevenDayTrajectory: "7-दिवसीय प्रक्षेपवक्र", hassanCoopDesk: "हसन जिला डेयरी संघ · मार्ग 4 सहकारी डेस्क", registeredFarms: "पंजीकृत फार्म", activeAnimals: "सक्रिय मवेशी", telemetrySyncRate: "टेलीमेट्री सिंक दर", subclinicalFlags: "सबक्लिनिकल झंडे", highRisk: "उच्च जोखिम", medRisk: "मध्यम जोखिम", allLowRisk: "सभी कम जोखिम", normalRisk: "सामान्य", weeklyTrendChange: "-28% पिछले सप्ताह की तुलना में", explainableAi: "व्याख्या योग्य एआई", featureTransparencyPanel: "विशेषता पारदर्शिता पैनल", transparencyIntro: "सबक्लिनिकल जोखिम पूर्वानुमान वास्तविक चालकता और तापमान डेटा पर प्रशिक्षित न्यूरल नेटवर्क मॉडल द्वारा उत्पन्न होते हैं। दोनों इनपुट जोखिम का आकलन करने में योगदान करते हैं।", conductivityFeatureName: "Milk_Conductivity (दूध की चालकता)", conductivityFeatureRole: "प्राथमिक सेंसर संकेत · प्रत्यक्ष माप", conductivityFeatureDesc: "दूध में Na⁺ और Cl⁻ आयन सांद्रता में बदलाव को मापता है। बढ़ी हुई विद्युत चालकता सीधे सबक्लिनिकल कोशिका झिल्ली परिवर्तन का संकेत देती है।", temperatureFeatureName: "Milk_Temperature (दूध का तापमान)", temperatureFeatureRole: "द्वितीयक सेंसर संकेत · सह-कारक", temperatureFeatureDesc: "तापमान भिन्नता को पकड़ता है। न्यूरल नेटवर्क में चालकता के साथ मिलकर, यह सामान्य उतार-चढ़ाव से शुरुआती बदलावों को अलग करने में मदद करता है।", vetFeedbackNote: "मॉडल सत्यापन: वास्तविक चालकता और तापमान डेटा 2-विशेषता न्यूरल नेटवर्क को फीड करता है। नैदानिक प्रतिक्रिया क्षेत्रीय सीमा सटीकता को मजबूत करती है।", impactTechnologyRoadmap: "प्रभाव और प्रौद्योगिकी रोडमैप", subclinicalIntelligenceEconomicProtection: "सबक्लिनिकल इंटेलिजेंस और आर्थिक सुरक्षा", pitchIntro: "पशु-मित्र मवेशियों के स्वास्थ्य की समय पर चेतावनी देकर नुकसान को रोकता है।", card1Badge: "2-4 दिन पहले चेतावनी", card1Title: "प्रारंभिक पूर्वानुमान बनाम नैदानिक पहचान", card1Body: "पारंपरिक नैदानिक पहचान शारीरिक लक्षण दिखने के बाद होती है। पशु-मित्र लक्षण दिखने से 2-4 दिन पहले आयनिक बदलावों और तापमान में सूक्ष्म परिवर्तन को ट्रैक करता है।", card1Bullet1: "कोशिका सूजन से पहले आयनिक सांद्रता में बदलाव का पता लगाता है", card1Bullet2: "शुरुआती हर्बल/गैर-एंटीबायोटिक उपचार को सक्षम बनाता है", card1Bullet3: "स्थायी ऊतक क्षति और दूध हानि को रोकता है", card2Badge: "छोटे किसानों की सुरक्षा", card2Title: "भारतीय डेयरी अर्थशास्त्र और एएमआर शमन", card2Body: "भारत का 80%+ दूध छोटे किसानों से आता है। बीमारी का सही समय पर पता लगाने से किसानों की आय सुरक्षित होती है और एंटीबायोटिक दवाओं के अत्यधिक उपयोग को रोका जाता है।", card2Bullet1: "उपचार लागत और दूध के नुकसान में प्रति गाय ₹6k–₹10k बचाता है", card2Bullet2: "अंधाधुंध एंटीबायोटिक उपयोग को रोकता है", card2Bullet3: "सहकारी दूध गुणवत्ता मानकों की रक्षा करता है", card3Badge: "चरण 2 रोडमैप", card3Title: "हार्डवेयर प्रोटोटाइप और एज एमएल परिनियोजन", card3Body: "वर्तमान में ब्राउज़र-सत्यापित मॉडल के रूप में कार्य कर रहा है। चरण 2 में यह तकनीक सीधे हैंडहेल्ड डिवाइस पर काम करेगी।", card3Bullet1: "हैंडहेल्ड ईसी प्रोब और स्वचालित सेंसर", card3Bullet2: "बिना इंटरनेट के माइक्रोकंट्रोलर एज पर अनुमान", card3Bullet3: "डेयरी सहकारी समितियों के साथ निर्बाध सिंक" },
  mr: { weatherToday: "रविवार, ६ सप्टेंबर २०२६", weatherLocationLabel: "हसन, कर्नाटक", farmerProfile: "शेतकरी प्रोफाइल", profileSubtitle: "तुमची शेतकरी ओळख आणि डेअरीची माहिती.", farmerLabel: "शेतकरी", phoneLabel: "फोन", villageLabel: "गाव", memberSinceLabel: "सदस्यत्व", dairyLabel: "तुमची डेअरी", registeredDevices: "नोंदणीकृत उपकरणे", cowsRegistered: "नोंदणीकृत गायी", sensorDevices: "सेन्सर उपकरणे", currentPreference: "सध्याची पसंती", languageHelp: "स्टेट पिकरमधून संपूर्ण अॅपची भाषा बदलते.", changeLanguage: "राज्य / भाषा बदला", localVet: "तुमच्या भागातील पशुवैद्य", largeAnimalSpecialist: "मोठ्या प्राण्यांचे तज्ज्ञ", availableToday: "आज उपलब्ध · सकाळी ८ – संध्याकाळी ७", shareReading: "पशुवैद्याशी बोलताना रीडिंग दाखवा.", startDemoCall: "डेमो कॉल सुरू करा", demoInteraction: "डेमो संवाद · प्रत्यक्ष कॉल होणार नाही", sensorConnected: "सेन्सर जोडलेला", sensorLow: "बॅटरी कमी", sensorStale: "सेन्सर प्रतिसाद देत नाही", liveDemoFeed: "लाइव्ह डेमो फीड", callingVet: "डॉ. मीरा राव यांना कॉल केला जात आहे… (डेमो)", queuedReadings: "रीडिंग रांगेत आहेत — ऑनलाइन झाल्यावर सिंक होतील", syncedReadings: "रीडिंग सिंक झाली — कळप अद्ययावत आहे", backOnline: "पुन्हा ऑनलाइन", offlineOn: "ऑफलाइन मोड सुरू · रीडिंग या डिव्हाइसवर राहतील", vetConfirmedToast: "पशुवैद्याची पुष्टी नोंदली", falseAlarmToast: "चुकीची सूचना नोंदली", farmerOverview: "शेतकरी आढावा", farmTitle: "माझे फार्म", farmSubtitle: "आजच्या कळपाचे सोपे चित्र.", cowsRegisteredStat: "नोंदणीकृत गायी", currentHerd: "तुमचा सध्याचा कळप", sensorsConnected: "जोडलेले सेन्सर", sensorsNotResponding: "प्रतिसाद नाही", lowBattery: "बॅटरी कमी", watchSensors: "या सेन्सरकडे लक्ष द्या", herdTrend: "कळपाचा कल", averageRisk: "सरासरी धोका", recentCare: "अलीकडची काळजी", lastResolved: "शेवटची सोडवलेली सूचना", noResolved: "अजून सोडवलेले प्रकरण नाही", dayAgo: "दिवसापूर्वी", daysAgo: "दिवसांपूर्वी", basedOnAlerts: "या डेमोतील सर्वात अलीकडच्या पुष्टी किंवा सोडवलेल्या सूचनेवर आधारित.", sensorWatch: "सेन्सर निरीक्षण", sensorNotRespondingPlural: "सेन्सर प्रतिसाद देत नाहीत.", dueChecks: "तपासणी बाकी असलेल्या गायी", dueChecksBody: "आज या गायींची तपासणी झालेली नाही.", allChecked: "आज प्रत्येक गायीचे ताजे रीडिंग आहे.", thisWeek: "या आठवड्यात", readingsTaken: "घेतलेली रीडिंग", alertsRaised: "आलेल्या सूचना", alertsResolved: "सोडवलेल्या सूचना", advisory: "आजचा सल्ला", advisoryHigh: "आज लक्ष देणे आवश्यक आहे.", advisoryMedium: "आज थोडे अधिक लक्ष द्या.", advisoryGood: "तुमचा कळप चांगला आहे — सध्या कोणत्याही गायीला लक्षाची गरज नाही.", quickAccess: "जलद प्रवेश", openAlerts: "सूचना उघडा", contactVet: "पशुवैद्याशी संपर्क", useStatePicker: "भाषा बदलण्यासाठी वरचा स्टेट पिकर वापरा", searchAnimals: "प्राणी शोधा…", close: "बंद करा", actualFeed: "आजची दूध तपासणी", modelRisk: "AI धोका मॉडेल", modelRiskBody: "खऱ्या चालकता आणि तापमान डेटावर प्रशिक्षित. हे निदान नाही — योग्य वेळी पशुवैद्याशी बोलण्यास मदत करते.", riskScoreToday: "आजचा धोका स्कोअर", infectionProbability: "संसर्ग धोक्याची शक्यता", days: "दिवस", continuousHistory: "सतत निरीक्षण", routineTitle: "चांगली सवय सुरू ठेवा", routineBody: "दररोज सकाळचे एक रीडिंग कळपाची स्थिती स्पष्ट ठेवते.", alertSubtitle: "प्रत्येक सूचना पुढचे योग्य पाऊल सांगते.", farmTrendNote: "कमी स्कोअर साधारणपणे शांत स्थिती दाखवतात. हा तुमच्या सध्याच्या रीडिंगचा आढावा आहे.", demoDerived: "डेमोमधून तयार केलेला सारांश · सध्याच्या रीडिंगनुसार बदलतो", checkNow: "आता तपासा", noAnimals: "कोणताही प्राणी जुळला नाही", vetValidationNote: "पशुवैद्याची पुष्टी पुढील रीडिंग सुधारते.", dateToday: "रविवार, ६ सप्टेंबर २०२६" },
  gu: {
    weatherToday: "રવિવાર, 6 સપ્ટેમ્બર 2026", weatherLocationLabel: "હસન, કર્ણાટક", farmerProfile: "ખેડૂત પ્રોફાઇલ", profileSubtitle: "તમારી ખેડૂત ઓળખ અને ડેરીની વિગતો.", farmerLabel: "ખેડૂત", phoneLabel: "ફોન", villageLabel: "ગામ", memberSinceLabel: "સભ્ય બન્યા", dairyLabel: "તમારી ડેરી", registeredDevices: "નોંધાયેલા ઉપકરણો", cowsRegistered: "નોંધાયેલી ગાયો", sensorDevices: "સેન્સર ઉપકરણો", currentPreference: "વર્તમાન પસંદગી", languageHelp: "સ્ટેટ પિકરથી આખી એપની ભાષા બદલાય છે.", changeLanguage: "રાજ્ય / ભાષા બદલો", localVet: "તમારા વિસ્તારના પશુચિકિત્સક", largeAnimalSpecialist: "મોટા પ્રાણીઓના નિષ્ણાત", availableToday: "આજે ઉપલબ્ધ · સવારે 8 – સાંજે 7", shareReading: "પશુચિકિત્સક સાથે વાત કરતી વખતે રીડિંગ બતાવો.", startDemoCall: "ડેમો કૉલ શરૂ કરો", demoInteraction: "ડેમો ક્રિયાપ્રતિક્રિયા · કોઈ વાસ્તવિક કૉલ કરવામાં આવશે નહીં", sensorConnected: "સેન્સર જોડાયેલો", sensorLow: "બેટરી ઓછી", sensorStale: "સેન્સર જવાબ આપતું નથી", liveDemoFeed: "લાઇવ ડેમો ફીડ", callingVet: "ડૉ. મીરા રાવને કૉલ કરી રહ્યા છીએ… (ડેમો)", queuedReadings: "રીડિંગ્સ કતારમાં છે — ઑનલાઇન થવા પર સિંક થશે", syncedReadings: "કતારબદ્ધ રીડિંગ્સ સિંક થઈ — ટોળું અપડેટ છે", backOnline: "ફરી ઑનલાઇન", offlineOn: "ઑફલાઇન મોડ ચાલુ — રીડિંગ્સ આ ઉપકરણ પર રહેશે", vetConfirmedToast: "પશુચિકિત્સકની પુષ્ટિ નોંધાઈ", falseAlarmToast: "ખોટી ચેતવણી તરીકે દર્જ કરી", farmerOverview: "ખેડૂત અવલોકન", farmTitle: "મારું ફાર્મ", farmSubtitle: "આજે તમારા ટોળાની સરળ તસવીર.", cowsRegisteredStat: "નોંધાયેલી ગાયો", currentHerd: "તમારું વર્તમાન ટોળું", sensorsConnected: "જોડાયેલા સેન્સર", sensorsNotResponding: "જવાબ આપતા નથી", lowBattery: "બેટરી ઓછી", watchSensors: "આ સેન્સર પર ધ્યાન આપો", herdTrend: "ટોળાનો ટ્રેન્ડ", averageRisk: "સરેરાશ જોખમ સ્કોર", recentCare: "તાજેતરની સંભાળ", lastResolved: "છેલ્લી ઉકેલાયેલી સૂચના", noResolved: "હજુ કોઈ કેસ ઉકેલાયો નથી", dayAgo: "દિવસ પહેલાં", daysAgo: "દિવસ પહેલાં", basedOnAlerts: "આ ડેમોમાં સૌથી તાજેતરની પુષ્ટિ થયેલી અથવા ઉકેલાયેલી સૂચના પર આધારિત.", sensorWatch: "સેન્સર ધ્યાન", sensorNotRespondingPlural: "સેન્સર જવાબ આપતા નથી.", dueChecks: "તપાસ બાકી ગાયો", dueChecksBody: "આ ગાયોની આજે તપાસ થઈ નથી.", allChecked: "આજે દરેક ગાયનું તાજું રીડિંગ છે.", thisWeek: "આ અઠવાડિયે", readingsTaken: "લેવામાં આવેલા રીડિંગ", alertsRaised: "ઊભી થયેલી સૂચનાઓ", alertsResolved: "ઉકેલાયેલી સૂચનાઓ", advisory: "આજની સલાહ", advisoryHigh: "આજે ધ્યાન જરૂરી છે.", advisoryMedium: "આજે થોડું વધુ ધ્યાન જોઈએ.", advisoryGood: "તમારું ટોળું સારું છે — અત્યારે કોઈ ગાયને ધ્યાનની જરૂર નથી.", quickAccess: "ઝડપી ઍક્સેસ", openAlerts: "સૂચનાઓ ખોલો", contactVet: "પશુચિકિત્સકનો સંપર્ક", useStatePicker: "ભાષા બદલવા ઉપરનો સ્ટેટ પિકર વાપરો", searchAnimals: "પ્રાણીઓ શોધો…", close: "બંધ કરો", actualFeed: "આજની દૂધ તપાસ", modelRisk: "AI જોખમ મોડેલ", modelRiskBody: "વાસ્તવિક વાહકતા અને તાપમાન ડેટા પર તાલીમ પામેલ. આ નિદાન નથી — તે તમને યોગ્ય સમયે પશુચિકિત્સક સાથે વાત કરવામાં મદદ કરે છે.", riskScoreToday: "આજનો જોખમ સ્કોર", infectionProbability: "ચેપ જોખમની સંભાવના", days: "દિવસ", continuousHistory: "સતત ઇતિહાસ", routineTitle: "સારી ટેવ ચાલુ રાખો", routineBody: "દિવસે એક વાર સવારનું રીડિંગ તમારા ટોળાની સ્થિતિ સ્પષ્ટ રાખે છે.", alertSubtitle: "દરેક સૂચના તમને આગામી સ્પષ્ટ પગલું આપે છે.", farmTrendNote: "ઓછા સ્કોર સામાન્ય રીતે શાંત સ્થિતિ બતાવે છે. આ તમારા હાલના રીડિંગનો સાર છે.", demoDerived: "ડેમો પરથી મેળવેલ સારાઉંશ · વર્તમાન રીડિંગ સાથે અપડેટ થાય છે", checkNow: "હમણાં તપાસો", noAnimals: "કોઈ પ્રાણી મળ્યું નથી", vetValidationNote: "પશુચિકિત્સકની પુષ્ટિ આગામી રીડિંગ સુધારે છે.", dateToday: "રવિવાર, 6 સપ્ટેમ્બર 2026"
  },
  pa: {
    weatherToday: "ਐਤਵਾਰ, 6 ਸਤੰਬਰ 2026", weatherLocationLabel: "ਹਾਸਨ, ਕਰਨਾਟਕ", farmerProfile: "ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ", profileSubtitle: "ਤੁਹਾਡੀ ਕਿਸਾਨ ਪਛਾਣ ਅਤੇ ਡੇਅਰੀ ਦੀ ਜਾਣਕਾਰੀ।", farmerLabel: "ਕਿਸਾਨ", phoneLabel: "ਫੋਨ", villageLabel: "ਪਿੰਡ", memberSinceLabel: "ਮੈਂਬਰ ਬਣੇ", dairyLabel: "ਤੁਹਾਡੀ ਡੇਅਰੀ", registeredDevices: "ਰਜਿਸਟਰ ਕੀਤੇ ਉਪਕਰਨ", cowsRegistered: "ਰਜਿਸਟਰ ਗਾਵਾਂ", sensorDevices: "ਸੈਂਸਰ ਉਪਕਰਨ", currentPreference: "ਮੌਜੂਦਾ ਪਸੰਦ", languageHelp: "ਸਟੇਟ ਪਿਕਰ ਨਾਲ ਪੂਰੇ ਐਪ ਦੀ ਭਾਸ਼ਾ ਬਦਲਦੀ ਹੈ।", changeLanguage: "ਰਾਜ / ਭਾਸ਼ਾ ਬਦਲੋ", localVet: "ਤੁਹਾਡੇ ਇਲਾਕੇ ਦੇ ਪਸ਼ੂ ਡਾਕਟਰ", largeAnimalSpecialist: "ਵੱਡੇ ਪਸ਼ੂਆਂ ਦੇ ਮਾਹਿਰ", availableToday: "ਅੱਜ ਉਪਲਬਧ · ਸਵੇਰੇ 8 – ਸ਼ਾਮ 7", shareReading: "ਪਸ਼ੂ ਡਾਕਟਰ ਨਾਲ ਗੱਲ ਕਰਦੇ ਸਮੇਂ ਰੀਡਿੰਗ ਦਿਖਾਓ।", startDemoCall: "ਡੈਮੋ ਕਾਲ ਸ਼ੁਰੂ ਕਰੋ", demoInteraction: "ਡੈਮੋ ਗੱਲਬਾਤ · ਕੋਈ ਅਸਲੀ ਕਾਲ ਨਹੀਂ ਹੋਵੇਗੀ", sensorConnected: "ਸੈਂਸਰ ਜੁੜਿਆ", sensorLow: "ਬੈਟਰੀ ਘੱਟ", sensorStale: "ਸੈਂਸਰ ਜਵਾਬ ਨਹੀਂ ਦੇ ਰਿਹਾ", liveDemoFeed: "ਲਾਈਵ ਡੈਮੋ ਫੀਡ", callingVet: "ਡਾ. ਮੀਰਾ ਰਾਵ ਨੂੰ ਕਾਲ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ… (ਡੈਮੋ)", queuedReadings: "ਰੀਡਿੰਗਾਂ ਕਤਾਰ ਵਿੱਚ ਹਨ — ਆਨਲਾਈਨ ਹੋਣ ਤੇ ਸਿੰਕ ਹੋਣਗੀਆਂ", syncedReadings: "ਕਤਾਰਬੱਧ ਰੀਡਿੰਗਾਂ ਸਿੰਕ ਹੋ ਗਈਆਂ — ਝੁੰਡ ਅੱਪਡੇਟ ਹੈ", backOnline: "ਦੁਬਾਰਾ ਆਨਲਾਈਨ", offlineOn: "ਆਫਲਾਈਨ ਮੋਡ ਚਾਲੂ — ਰੀਡਿੰਗਾਂ ਇਸ ਡਿਵਾਈਸ ਤੇ ਰਹਿਣਗੀਆਂ", vetConfirmedToast: "ਪਸ਼ੂ ਡਾਕਟਰ ਦੀ ਪੁਸ਼ਟੀ ਦਰਜ ਹੋਈ", falseAlarmToast: "ਗਲਤ ਚੇਤਾਵਨੀ ਦਰਜ ਕੀਤੀ", farmerOverview: "ਕਿਸਾਨ ਜਾਇਜ਼ਾ", farmTitle: "ਮੇਰਾ ਫਾਰਮ", farmSubtitle: "ਅੱਜ ਤੁਹਾਡੇ ਝੁੰਡ ਦੀ ਸਧਾਰਨ ਤਸਵੀਰ।", cowsRegisteredStat: "ਰਜਿਸਟਰ ਗਾਵਾਂ", currentHerd: "ਤੁਹਾਡਾ ਮੌਜੂਦਾ ਝੁੰਡ", sensorsConnected: "ਜੁੜੇ ਸੈਂਸਰ", sensorsNotResponding: "ਜਵਾਬ ਨਹੀਂ ਦੇ ਰਹੇ", lowBattery: "ਬੈਟਰੀ ਘੱਟ", watchSensors: "ਇਨ੍ਹਾਂ ਸੈਂਸਰਾਂ ਤੇ ਧਿਆਨ ਦਿਓ", herdTrend: "ਝੁੰਡ ਦਾ ਰੁਝਾਨ", averageRisk: "ਔਸਤ ਖਤਰਾ ਸਕੋਰ", recentCare: "ਹਾਲ ਦੀ ਦੇਖਭਾਲ", lastResolved: "ਆਖਰੀ ਹੱਲ ਹੋਈ ਸੂਚਨਾ", noResolved: "ਅਜੇ ਕੋਈ ਕੇਸ ਹੱਲ ਨਹੀਂ ਹੋਇਆ", dayAgo: "ਦਿਨ ਪਹਿਲਾਂ", daysAgo: "ਦਿਨ ਪਹਿਲਾਂ", basedOnAlerts: "ਇਸ ਡੈਮੋ ਦੀ ਸਭ ਤੋਂ ਤਾਜ਼ਾ ਪੁਸ਼ਟੀ ਜਾਂ ਹੱਲ ਹੋਈ ਸੂਚਨਾ ਤੇ ਆਧਾਰਿਤ।", sensorWatch: "ਸੈਂਸਰ ਧਿਆਨ", sensorNotRespondingPlural: "ਸੈਂਸਰ ਜਵਾਬ ਨਹੀਂ ਦੇ ਰਹੇ।", dueChecks: "ਜਿਨ੍ਹਾਂ ਗਾਵਾਂ ਦੀ ਜਾਂਚ ਬਾਕੀ ਹੈ", dueChecksBody: "ਅੱਜ ਇਨ੍ਹਾਂ ਗਾਵਾਂ ਦੀ ਜਾਂਚ ਨਹੀਂ ਹੋਈ।", allChecked: "ਅੱਜ ਹਰ ਗਾਂ ਦੀ ਤਾਜ਼ਾ ਰੀਡਿੰਗ ਹੈ।", thisWeek: "ਇਸ ਹਫ਼ਤੇ", readingsTaken: "ਲਈਆਂ ਰੀਡਿੰਗਾਂ", alertsRaised: "ਉੱਠੀਆਂ ਸੂਚਨਾਵਾਂ", alertsResolved: "ਹੱਲ ਹੋਈਆਂ ਸੂਚਨਾਵਾਂ", advisory: "ਅੱਜ ਦੀ ਸਲਾਹ", advisoryHigh: "ਨੂੰ ਅੱਜ ਧਿਆਨ ਦੀ ਲੋੜ ਹੈ।", advisoryMedium: "ਤੇ ਅੱਜ ਥੋੜ੍ਹਾ ਹੋਰ ਧਿਆਨ ਦਿਓ।", advisoryGood: "ਤੁਹਾਡਾ ਝੁੰਡ ਚੰਗਾ ਹੈ — ਹੁਣ ਕਿਸੇ ਗਾਂ ਨੂੰ ਧਿਆਨ ਦੀ ਲੋੜ ਨਹੀਂ।", quickAccess: "ਤੁਰੰਤ ਪਹੁੰਚ", openAlerts: "ਸੂਚਨਾਵਾਂ ਖੋਲ੍ਹੋ", contactVet: "ਪਸ਼ੂ ਡਾਕਟਰ ਨਾਲ ਸੰਪਰਕ", useStatePicker: "ਭਾਸ਼ਾ ਬਦਲਣ ਲਈ ਉੱਪਰਲਾ ਸਟੇਟ ਪਿਕਰ ਵਰਤੋ", searchAnimals: "ਜਾਨਵਰ ਖੋਜੋ…", close: "ਬੰਦ ਕਰੋ", actualFeed: "ਅੱਜ ਦੀ ਦੁੱਧ ਜਾਂਚ", modelRisk: "AI ਖਤਰਾ ਮਾਡਲ", modelRiskBody: "ਅਸਲੀ ਚਾਲਕਤਾ ਅਤੇ ਤਾਪਮਾਨ ਡਾਟਾ ਤੇ ਸਿਖਲਾਈ ਪ੍ਰਾਪਤ। ਇਹ ਨਿਦਾਨ ਨਹੀਂ ਹੈ — ਇਹ ਸਹੀ ਸਮੇਂ ਤੇ ਪਸ਼ੂ ਡਾਕਟਰ ਨਾਲ ਗੱਲ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ।", riskScoreToday: "ਅੱਜ ਦਾ ਖਤਰਾ ਸਕੋਰ", infectionProbability: "ਇਨਫੈਕਸ਼ਨ ਖਤਰੇ ਦੀ ਸੰਭਾਵਨਾ", days: "ਦਿਨ", continuousHistory: "ਨਿਰੰਤਰ ਇਤਿਹਾਸ", routineTitle: "ਚੰਗੀ ਆਦਤ ਜਾਰੀ ਰੱਖੋ", routineBody: "ਦਿਨ ਵਿੱਚ ਇੱਕ ਵਾਰ ਸਵੇਰ ਦੀ ਰੀਡਿੰਗ ਤੁਹਾਡੇ ਝੁੰਡ ਦੀ ਸਥਿਤੀ ਸਾਫ਼ ਰੱਖਦੀ ਹੈ।", alertSubtitle: "ਹਰ ਸੂਚਨਾ ਤੁਹਾਨੂੰ ਅਗਲਾ ਸਪਸ਼ਟ ਕਦਮ ਦੱਸਦੀ ਹੈ।", farmTrendNote: "ਘੱਟ ਸਕੋਰ ਆਮ ਤੌਰ ਤੇ ਸ਼ਾਂਤ ਹਾਲਤ ਦਿਖਾਉਂਦੇ ਹਨ। ਇਹ ਮੌਜੂਦਾ ਰੀਡਿੰਗਾਂ ਦਾ ਸਾਰ ਹੈ।", demoDerived: "ਡੈਮੋ ਤੋਂ ਨਿਕਲਿਆ ਸਾਰ · ਮੌਜੂਦਾ ਰੀਡਿੰਗਾਂ ਨਾਲ ਅੱਪਡੇਟ ਹੁੰਦਾ ਹੈ", checkNow: "ਹੁਣੇ ਜਾਂਚੋ", noAnimals: "ਕੋਈ ਜਾਨਵਰ ਨਹੀਂ ਮਿਲਿਆ", vetValidationNote: "ਪਸ਼ੂ ਡਾਕਟਰ ਦੀ ਪੁਸ਼ਟੀ ਅਗਲੀ ਰੀਡਿੰਗ ਸੁਧਾਰਦੀ ਹੈ।", dateToday: "ਐਤਵਾਰ, 6 ਸਤੰਬਰ 2026"
  },
  kn: {
    weatherToday: "ಭಾನುವಾರ, 6 ಸೆಪ್ಟೆಂಬರ್ 2026", weatherLocationLabel: "ಹಾಸನ, ಕರ್ನಾಟಕ", farmerProfile: "ರೈತ ಪ್ರೊಫೈಲ್", profileSubtitle: "ನಿಮ್ಮ ರೈತ ಗುರುತು ಮತ್ತು ಡೇರಿಯ ವಿವರಗಳು.", farmerLabel: "ರೈತ", phoneLabel: "ದೂರವಾಣಿ", villageLabel: "ಹಳ್ಳಿ", memberSinceLabel: "ಸದಸ್ಯರಾದ ದಿನ", dairyLabel: "ನಿಮ್ಮ ಡೇರಿ", registeredDevices: "ನೋಂದಾಯಿತ ಸಾಧನಗಳು", cowsRegistered: "ನೋಂದಾಯಿತ ಹಸುಗಳು", sensorDevices: "ಸೆನ್ಸರ್ ಸಾಧನಗಳು", currentPreference: "ಪ್ರಸ್ತುತ ಆಯ್ಕೆ", languageHelp: "ಸ್ಟೇಟ್ ಪಿಕರ್ ಇಡೀ ಆ್ಯಪ್‌ನ ಭಾಷೆಯನ್ನು ಬದಲಿಸುತ್ತದೆ.", changeLanguage: "ರಾಜ್ಯ / ಭಾಷೆ ಬದಲಿಸಿ", localVet: "ನಿಮ್ಮ ಸ್ಥಳೀಯ ಪಶುವೈದ್ಯರು", largeAnimalSpecialist: "ದೊಡ್ಡ ಪ್ರಾಣಿಗಳ ತಜ್ಞರು", availableToday: "ಇಂದು ಲಭ್ಯ · ಬೆಳಗ್ಗೆ 8 – ಸಂಜೆ 7", shareReading: "ಪಶುವೈದ್ಯರೊಂದಿಗೆ ಮಾತನಾಡುವಾಗ ರೀಡಿಂಗ್ ತೋರಿಸಿ.", startDemoCall: "ಡೆಮೋ ಕರೆ ಪ್ರಾರಂಭಿಸಿ", demoInteraction: "ಡೆಮೋ ಸಂವಹನ · ಯಾವುದೇ ನೈಜ ಕರೆ ಇರುವುದಿಲ್ಲ", sensorConnected: "ಸೆನ್ಸರ್ ಸಂಪರ್ಕಗೊಂಡಿದೆ", sensorLow: "ಬ್ಯಾಟರಿ ಕಡಿಮೆ", sensorStale: "ಸೆನ್ಸರ್ ಪ್ರತಿಕ್ರಿಯಿಸುತ್ತಿಲ್ಲ", liveDemoFeed: "ಲೈವ್ ಡೆಮೋ ಫೀಡ್", callingVet: "ಡಾ. ಮೀರಾ ರಾವ್ ಅವರಿಗೆ ಕರೆ ಮಾಡಲಾಗುತ್ತಿದೆ… (ಡೆಮೋ)", queuedReadings: "ರೀಡಿಂಗ್‌ಗಳು ಸಾಲಿನಲ್ಲಿವೆ — ಆನ್‌ಲೈನ್ ಬಂದಾಗ ಸಿಂಕ್ ಆಗುತ್ತವೆ", syncedReadings: "ಸಾಲಿನ ರೀಡಿಂಗ್‌ಗಳು ಸಿಂಕ್ ಆಗಿವೆ — ಹಿಂಡು ಅಪ್‌ಡೇಟ್ ಆಗಿದೆ", backOnline: "ಮತ್ತೆ ಆನ್‌ಲೈನ್", offlineOn: "ಆಫ್‌ಲೈನ್ ಮೋಡ್ ಆನ್ — ರೀಡಿಂಗ್‌ಗಳು ಈ ಸಾಧನದಲ್ಲಿರುತ್ತವೆ", vetConfirmedToast: "ಪಶುವೈದ್ಯರ ದೃಢೀಕರಣ ದಾಖಲಾಗಿದೆ", falseAlarmToast: "ಸುಳ್ಳು ಎಚ್ಚರಿಕೆ ಎಂದು ನಮೂದಿಸಲಾಗಿದೆ", farmerOverview: "ರೈತ ಅವಲೋಕನ", farmTitle: "ನನ್ನ ಫಾರ್ಮ್", farmSubtitle: "ಇಂದು ನಿಮ್ಮ ಹಿಂಡಿನ ಸರಳ ಚಿತ್ರ.", cowsRegisteredStat: "ನೋಂದಾಯಿತ ಹಸುಗಳು", currentHerd: "ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಹಿಂಡು", sensorsConnected: "ಸಂಪರ್ಕಿತ ಸೆನ್ಸರ್‌ಗಳು", sensorsNotResponding: "ಪ್ರತಿಕ್ರಿಯಿಸುತ್ತಿಲ್ಲ", lowBattery: "ಬ್ಯಾಟರಿ ಕಡಿಮೆ", watchSensors: "ಈ ಸೆನ್ಸರ್‌ಗಳನ್ನು ಗಮನಿಸಿ", herdTrend: "ಹಿಂಡಿನ ಪ್ರವೃತ್ತಿ", averageRisk: "ಸರಾಸರಿ ಅಪಾಯ ಸ್ಕೋರ್", recentCare: "ಇತ್ತೀಚಿನ ಆರೈಕೆ", lastResolved: "ಕೊನೆಯ ಪರಿಹಾರವಾದ ಎಚ್ಚರಿಕೆ", noResolved: "ಇನ್ನೂ ಪರಿಹಾರವಾದ ಪ್ರಕರಣವಿಲ್ಲ", dayAgo: "ದಿನದ ಹಿಂದೆ", daysAgo: "ದಿನಗಳ ಹಿಂದೆ", basedOnAlerts: "ಈ ಡೆಮೋದ ಇತ್ತೀಚಿನ ದೃಢೀಕರಿಸಿದ ಅಥವಾ ಪರಿಹಾರವಾದ ಎಚ್ಚರಿಕೆಯನ್ನು ಆಧರಿಸಿದೆ.", sensorWatch: "ಸೆನ್ಸರ್ ಗಮನ", sensorNotRespondingPlural: "ಸೆನ್ಸರ್‌ಗಳು ಪ್ರತಿಕ್ರಿಯಿಸುತ್ತಿಲ್ಲ.", dueChecks: "ಪರೀಕ್ಷೆ ಬಾಕಿ ಇರುವ ಹಸುಗಳು", dueChecksBody: "ಈ ಹಸುಗಳನ್ನು ಇಂದು ಪರೀಕ್ಷಿಸಲಾಗಿಲ್ಲ.", allChecked: "ಇಂದು ಪ್ರತಿಯೊಂದು ಹಸುವಿಗೂ ಹೊಸ ರೀಡಿಂಗ್ ಇದೆ.", thisWeek: "ಈ ವಾರ", readingsTaken: "ತೆಗೆದ ರೀಡಿಂಗ್‌ಗಳು", alertsRaised: "ಎದ್ದ ಎಚ್ಚರಿಕೆಗಳು", alertsResolved: "ಪರಿಹಾರವಾದ ಎಚ್ಚರಿಕೆಗಳು", advisory: "ಇಂದಿನ ಸಲಹೆ", advisoryHigh: "ಗೆ ಇಂದು ಗಮನ ಬೇಕು.", advisoryMedium: "ಇಂದು ಸ್ವಲ್ಪ ಹೆಚ್ಚು ಗಮನ ಬೇಕು.", advisoryGood: "ನಿಮ್ಮ ಹಿಂಡು ಚೆನ್ನಾಗಿದೆ — ಈಗ ಯಾವುದೇ ಹಸುವಿಗೆ ವಿಶೇಷ ಗಮನ ಬೇಕಿಲ್ಲ.", quickAccess: "ತ್ವರಿತ ಪ್ರವೇಶ", openAlerts: "ಎಚ್ಚರಿಕೆ ತೆರೆಯಿರಿ", contactVet: "ಪಶುವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ", useStatePicker: "ಭಾಷೆ ಬದಲಿಸಲು ಮೇಲಿನ ಸ್ಟೇಟ್ ಪಿಕರ್ ಬಳಸಿ", searchAnimals: "ಪ್ರಾಣಿಗಳನ್ನು ಹುಡುಕಿ…", close: "ಮುಚ್ಚಿ", actualFeed: "ಇಂದಿನ ಹಾಲಿನ ತಪಾಸಣೆ", modelRisk: "AI ಅಪಾಯದ ಮಾದರಿ", modelRiskBody: "ನೈಜ ವಾಹಕತೆ ಮತ್ತು ತಾಪಮಾನ ಡೇಟಾದ ಮೇಲೆ ತರಬೇತಿ ನೀಡಲಾಗಿದೆ. ಇದು ರೋಗನಿರ್ಣಯವಲ್ಲ — ಸೂಕ್ತ ಸಮಯದಲ್ಲಿ ಪಶುವೈದ್ಯರೊಂದಿಗೆ ಮಾತನಾಡಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.", riskScoreToday: "ಇಂದಿನ ಅಪಾಯ ಸ್ಕೋರ್", infectionProbability: "ಸಂಕ್ರಮಣ ಅಪಾಯದ ಸಾಧ್ಯತೆ", days: "ದಿನಗಳು", continuousHistory: "ನಿರಂತರ ಇತಿಹಾಸ", routineTitle: "ಒಳ್ಳೆಯ ಅಭ್ಯಾಸ ಮುಂದುವರಿಸಿ", routineBody: "ದಿನಕ್ಕೆ ಒಮ್ಮೆ ಬೆಳಗಿನ ರೀಡಿಂಗ್ ನಿಮ್ಮ ಹಿಂಡಿನ ಸ್ಥಿತಿಯನ್ನು ಸ್ಪಷ್ಟವಾಗಿಡುತ್ತದೆ.", alertSubtitle: "ಪ್ರತಿಯೊಂದು ಎಚ್ಚರಿಕೆಯು ನಿಮಗೆ ಮುಂದಿನ ಸ್ಪಷ್ಟ ಹೆಜ್ಜೆಯನ್ನು ನೀಡುತ್ತದೆ.", farmTrendNote: "ಕಡಿಮೆ ಸ್ಕೋರ್‌ಗಳು ಸಾಮಾನ್ಯವಾಗಿ ಶಾಂತ ಸ್ಥಿತಿಯನ್ನು ತೋರಿಸುತ್ತವೆ. ಇದು ನಿಮ್ಮ ಇತ್ತೀಚಿನ ರೀಡಿಂಗ್‌ಗಳ ಸಾರಾಂಶ.", demoDerived: "ಡೆಮೋ ಆಧಾರಿತ ಸಾರಾಂಶ · ಪ್ರಸ್ತುತ ರೀಡಿಂಗ್‌ಗಳೊಂದಿಗೆ ಅಪ್‌ಡೇಟ್ ಆಗುತ್ತದೆ", checkNow: "ಈಗ ಪರೀಕ್ಷಿಸಿ", noAnimals: "ಯಾವುದೇ ಪ್ರಾಣಿ ಸಿಗಲಿಲ್ಲ", vetValidationNote: "ಪಶುವೈದ್ಯರ ಪರಿಶೀಲನೆಯು ಮುಂದಿನ ರೀಡಿಂಗ್ ಅನ್ನು ಉತ್ತಮಗೊಳಿಸುತ್ತದೆ.", dateToday: "ಭಾನುವಾರ, 6 ಸೆಪ್ಟೆಂಬರ್ 2026"
  },
  ta: {
    weatherToday: "ஞாயிறு, 6 செப்டம்பர் 2026", weatherLocationLabel: "ஹாசன், கர்நாடகா", farmerProfile: "விவசாயி சுயவிவரம்", profileSubtitle: "உங்கள் விவசாயி அடையாளம் மற்றும் பால் பண்ணை விவரங்கள்.", farmerLabel: "விவசாயி", phoneLabel: "தொலைபேசி", villageLabel: "கிராமம்", memberSinceLabel: "உறுப்பினர் முதல்", dairyLabel: "உங்கள் பண்ணை", registeredDevices: "பதிவு செய்யப்பட்ட சாதனங்கள்", cowsRegistered: "பதிவு செய்யப்பட்ட மாடுகள்", sensorDevices: "சென்சார் சாதனங்கள்", currentPreference: "தற்போதைய விருப்பம்", languageHelp: "நிலத் தேர்வி முழு செயலியின் மொழியை மாற்றுகிறது.", changeLanguage: "மாநிலம் / மொழியை மாற்று", localVet: "உங்கள் உள்ளூர் கால்நடை மருத்துவர்", largeAnimalSpecialist: "பெரிய விலங்கு நிபுணர்", availableToday: "இன்று கிடைக்கும் · காலை 8 – மாலை 7", shareReading: "மருத்துவரிடம் பேசும்போது வாசிப்பைக் காட்டுங்கள்.", startDemoCall: "டெமோ அழைப்பைத் தொடங்கு", demoInteraction: "டெமோ தொடர்பு · உண்மையான அழைப்பு இருக்காது", sensorConnected: "சென்சார் இணைக்கப்பட்டது", sensorLow: "பேட்டரி குறைவு", sensorStale: "சென்சார் பதிலளிக்கவில்லை", liveDemoFeed: "நேரடி டெமோ ஊட்டம்", callingVet: "டாக்டர் மீரா ராவ் அவர்களுக்கு அழைப்பு விடுக்கப்படுகிறது… (டெமோ)", queuedReadings: "வாசிப்புகள் வரிசையில் உள்ளன — ஆன்லைனில் வந்ததும் சிங்கிங் ஆகும்", syncedReadings: "வரிசை வாசிப்புகள் சிங்கிங் செய்யப்பட்டன — மந்தை புதுப்பிக்கப்பட்டது", backOnline: "மீண்டும் ஆன்லைனில்", offlineOn: "ஆஃப்லைன் பயன்முறை ஆன் — வாசிப்புகள் இந்த சாதனத்தில் இருக்கும்", vetConfirmedToast: "கால்நடை மருத்துவர் உறுதிப்படுத்தல் பதிவு செய்யப்பட்டது", falseAlarmToast: "தவறான எச்சரிக்கை என பதிவு செய்யப்பட்டது", farmerOverview: "விவசாயி கண்ணோட்டம்", farmTitle: "என் பண்ணை", farmSubtitle: "இன்று உங்கள் மந்தையின் எளிய படம்.", cowsRegisteredStat: "பதிவு செய்யப்பட்ட மாடுகள்", currentHerd: "உங்கள் தற்போதைய மந்தை", sensorsConnected: "இணைக்கப்பட்ட சென்சார்கள்", sensorsNotResponding: "பதிலளிக்கவில்லை", lowBattery: "பேட்டரி குறைவு", watchSensors: "இந்த சென்சார்களைக் கவனிக்கவும்", herdTrend: "மந்தை போக்கு", averageRisk: "சராசரி ஆபத்து மதிப்பெண்", recentCare: "சமீபத்திய பராமரிப்பு", lastResolved: "கடைசி தீர்க்கப்பட்ட எச்சரிக்கை", noResolved: "இதுவரை தீர்க்கப்பட்ட வழக்கு இல்லை", dayAgo: "நாள் முன்பு", daysAgo: "நாட்களுக்கு முன்பு", basedOnAlerts: "இந்த டெமோவின் சமீபத்திய உறுதி அல்லது தீர்க்கப்பட்ட எச்சரிக்கையை அடிப்படையாகக் கொண்டது.", sensorWatch: "சென்சார் கவனம்", sensorNotRespondingPlural: "சென்சார்கள் பதிலளிக்கவில்லை.", dueChecks: "சோதனை வேண்டிய மாடுகள்", dueChecksBody: "இந்த மாடுகள் இன்று சோதிக்கப்படவில்லை.", allChecked: "இன்று ஒவ்வொரு மாட்டுக்கும் புதிய வாசிப்பு உள்ளது.", thisWeek: "இந்த வாரம்", readingsTaken: "எடுக்கப்பட்ட வாசிப்புகள்", alertsRaised: "எழுந்த எச்சரிக்கைகள்", alertsResolved: "தீர்க்கப்பட்ட எச்சரிக்கைகள்", advisory: "இன்றைய ஆலோசனை", advisoryHigh: "இன்று கவனம் தேவை.", advisoryMedium: "இன்று சற்று கூடுதல் கவனம் தேவை.", advisoryGood: "உங்கள் மந்தை நன்றாக உள்ளது — இப்போது எந்த மாட்டுக்கும் சிறப்பு கவனம் தேவையில்லை.", quickAccess: "விரைவு அணுகல்", openAlerts: "எச்சரிக்கைகளைத் திற", contactVet: "மருத்துவரைத் தொடர்பு", useStatePicker: "மொழியை மாற்ற மேலுள்ள மாநிலத் தேர்வியைப் பயன்படுத்தவும்", searchAnimals: "விலங்குகளைத் தேடுங்கள்…", close: "மூடு", actualFeed: "இன்றைய பால் சோதனை", modelRisk: "AI ஆபத்து மாதிரி", modelRiskBody: "உண்மையான கடத்துத்திறன் மற்றும் வெப்பநிலை தரவில் பயிற்சி பெற்றது. இது நோயறிதல் அல்ல — சரியான நேரத்தில் மருத்துவரிடம் பேச உதவுகிறது.", riskScoreToday: "இன்றைய ஆபத்து மதிப்பெண்", infectionProbability: "தொற்று ஆபத்து சாத்தியக்கூறு", days: "நாட்கள்", continuousHistory: "தொடர்ச்சியான வரலாறு", routineTitle: "நல்ல பழக்கத்தைத் தொடருங்கள்", routineBody: "நாளைக்கு ஒரு முறை காலை வாசிப்பு உங்கள் மந்தையின் நிலையை தெளிவாக வைக்கும்.", alertSubtitle: "ஒவ்வொரு எச்சரிக்கையும் அடுத்த தெளிவான படியை உங்களுக்கு வழங்கும்.", farmTrendNote: "குறைந்த மதிப்பெண்கள் பொதுவாக அமைதியான நிலையை காட்டும். இது உங்கள் தற்போதைய வாசிப்புகளின் சுருக்கம்.", demoDerived: "டெமோ மூல சுருக்கம் · தற்போதைய வாசிப்புகளுடன் புதுப்பிக்கப்படும்", checkNow: "இப்போது சோதிக்கவும்", noAnimals: "எந்த விலங்கும் கிடைக்கவில்லை", vetValidationNote: "கால்நடை மருத்துவர் சரிபார்ப்பு அடுத்த வாசிப்பை மேம்படுத்துகிறது.", dateToday: "ஞாயிறு, 6 செப்டம்பர் 2026"
  },
  te: {
    weatherToday: "ఆదివారం, 6 సెప్టెంబర్ 2026", weatherLocationLabel: "హాసన్, కర్ణాటక", farmerProfile: "రైతు ప్రొఫైల్", profileSubtitle: "మీ రైతు గుర్తింపు మరియు డెయిరీ వివరాలు.", farmerLabel: "రైతు", phoneLabel: "ఫోన్", villageLabel: "గ్రామం", memberSinceLabel: "సభ్యత్వం ప్రారంభం", dairyLabel: "మీ డెయిరీ", registeredDevices: "నమోదైన పరికరాలు", cowsRegistered: "నమోదైన ఆవులు", sensorDevices: "సెన్సర్ పరికరాలు", currentPreference: "ప్రస్తుత ఎంపిక", languageHelp: "స్టేట్ పికర్ మొత్తం యాప్ భాషను మారుస్తుంది.", changeLanguage: "రాష్ట్రం / భాష మార్చండి", localVet: "మీ స్థానిక పశువైద్యుడు", largeAnimalSpecialist: "పెద్ద జంతువుల నిపుణుడు", availableToday: "ఈ రోజు అందుబాటులో · ఉదయం 8 – సాయంత్రం 7", shareReading: "పశువైద్యుడితో మాట్లాడేటప్పుడు రీడింగ్ చూపించండి.", startDemoCall: "డెమో కాల్ ప్రారంభించండి", demoInteraction: "డెమో సంభాషణ · నిజమైన కాల్ ఉండదు", sensorConnected: "సెన్సర్ అనుసంధానమైంది", sensorLow: "బ్యాటరీ తక్కువ", sensorStale: "సెన్సర్ స్పందించడం లేదు", liveDemoFeed: "లైవ్ డెమో ఫీడ్", callingVet: "డాక్టర్ మీరా రావు గారికి కాల్ చేస్తున్నారు… (డెమో)", queuedReadings: "రీడింగ్‌లు క్యూలో ఉన్నాయి — ఆన్‌లైన్‌లోకి రాగానే సింక్ అవుతాయి", syncedReadings: "క్యూలోని రీడింగ్‌లు సింక్ అయ్యాయి — మంద సమాచారం అప్‌డేట్ అయింది", backOnline: "మళ్లీ ఆన్‌లైన్", offlineOn: "ఆఫ్‌లైన్ మోడ్ ఆన్ — రీడింగ్‌లు ఈ పరికరంలో ఉంటాయి", vetConfirmedToast: "పశువైద్యుడి దృవీకరణ నమోదు చేయబడింది", falseAlarmToast: "తప్పు హెచ్చరికగా నమోదు చేయబడింది", farmerOverview: "రైతు అవలోకనం", farmTitle: "నా ఫారం", farmSubtitle: "ఈ రోజు మీ మంద యొక్క సరళమైన చిత్రం.", cowsRegisteredStat: "నమోదైన ఆవులు", currentHerd: "మీ ప్రస్తుత మంద", sensorsConnected: "అనుసంధానమైన సెన్సర్లు", sensorsNotResponding: "స్పందించడం లేదు", lowBattery: "బ్యాటరీ తక్కువ", watchSensors: "ఈ సెన్సర్లను గమనించండి", herdTrend: "మంద ధోరణి", averageRisk: "సగటు ప్రమాద స్కోర్", recentCare: "ఇటీవలి సంరక్షణ", lastResolved: "చివరి పరిష్కరించిన హెచ్చరిక", noResolved: "ఇంకా పరిష్కరించిన కేసు లేదు", dayAgo: "రోజు క్రితం", daysAgo: "రోజుల క్రితం", basedOnAlerts: "ఈ డెమోలో ఇటీవలి నిర్ధారించిన లేదా పరిష్కరించిన హెచ్చరిక ఆధారంగా.", sensorWatch: "సెన్సర్ గమనిక", sensorNotRespondingPlural: "సెన్సర్లు స్పందించడం లేదు.", dueChecks: "తనిఖీ చేయాల్సిన ఆవులు", dueChecksBody: "ఈ ఆవులను ఈ రోజు తనిఖీ చేయలేదు.", allChecked: "ఈ రోజు ప్రతి ఆవుకు తాజా రీడింగ్ ఉంది.", thisWeek: "ఈ వారం", readingsTaken: "తీసిన రీడింగ్‌లు", alertsRaised: "వచ్చిన హెచ్చరికలు", alertsResolved: "పరిష్కరించిన హెచ్చరికలు", advisory: "ఈ రోజు సలహా", advisoryHigh: "కు ఈ రోజు శ్రద్ధ అవసరం.", advisoryMedium: "కు ఈ రోజు మరింత శ్రద్ధ అవసరం.", advisoryGood: "మీ మంద బాగుంది — ఇప్పుడు ఏ ఆవుకూ ప్రత్యేక శ్రద్ధ అవసరం లేదు.", quickAccess: "త్వరిత ప్రాప్యత", openAlerts: "హెచ్చరికలు తెరవండి", contactVet: "పశువైద్యుడిని సంప్రదించండి", useStatePicker: "భాష మార్చడానికి పై స్టేట్ పికర్‌ను ఉపయోగించండి", searchAnimals: "జంతువులను వెతకండి…", close: "మూసివేయి", actualFeed: "ఈ రోజు పాలు తనిఖీ", modelRisk: "AI ప్రమాద మోడల్", modelRiskBody: "వాస్తవ విద్యుత్ వాహకత మరియు ఉష్ణోగ్రత డేటా ఆధారంగా శిక్షణ పొందబడింది. ఇది వ్యాధి నిర్ధారణ కాదు — సమయానికి పశువైద్యుడితో మాట్లాడటానికి సహాయపడుతుంది.", riskScoreToday: "ఈ రోజు ప్రమాద స్కోర్", infectionProbability: "ఇన్ఫెక్షన్ ప్రమాద సంభావ్యత", days: "రోజులు", continuousHistory: "నిరంతర చరిత్ర", routineTitle: "మంచి అలవాటు కొనసాగించండి", routineBody: "రోజుకు ఒకసారి ఉదయం రీడింగ్ మీ మంద స్థితిని స్పష్టంగా ఉంచుతుంది.", alertSubtitle: "ప్రతి హెచ్చరిక మీకు తదుపరి స్పష్టమైన అడుగును అందిస్తుంది.", farmTrendNote: "తక్కువ స్కోర్లు సాధారణంగా ప్రశాంత స్థితిని సూచిస్తాయి. ఇది మీ ప్రస్తుత రీడింగ్‌ల సారాంశం.", demoDerived: "డెమో ఆధారిత సారాంశం · ప్రస్తుత రీడింగ్‌లతో అప్‌డేట్ అవుతుంది", checkNow: "ఇప్పుడే తనిఖీ చేయండి", noAnimals: "ఏ జంతువూ కనబడలేదు", vetValidationNote: "పశువైద్యుడి తనిఖీ తదుపరి రీడింగ్‌ను మెరుగుపరుస్తుంది.", dateToday: "ఆదివారం, 6 సెప్టెంబర్ 2026"
  }
}
export const localizedExtras: Record<Language, ExtraCopy> = Object.fromEntries(Object.entries(extraCopy).map(([key, value]) => [key, { ...extraCopy.en, ...value }])) as Record<Language, ExtraCopy>

export const surfaceCopy: Record<Language, { brandTagline: string; earlyWarning: string; heroLineOne: string; heroLineTwo: string; heroBody: string; modelNote: string; simulatedFeed: string; milkCheck: string; hardwareNote: string; conductivity: string; conductivityNote: string; temperature: string; temperatureNote: string; battery: string; batteryNote: string; staleNote: string; telemetryNote: string }> = {
  en: { brandTagline: "Healthy connections", earlyWarning: "Pashu Mitra early warning", heroLineOne: "Healthy cows.", heroLineTwo: "Peaceful mornings.", heroBody: "Check once a day. Know sooner. Care better.", modelNote: "Model updated from today’s readings", simulatedFeed: "Simulated sensor feed", milkCheck: "Today’s milk check", hardwareNote: "Hardware prototype in development", conductivity: "Electrical conductivity", conductivityNote: "Milk conductivity · rises with infection", temperature: "Milk temperature", temperatureNote: "Secondary signal · helps reduce false positives", battery: "Sensor battery", batteryNote: "Functional · battery degrades slowly", staleNote: "Sensor not responding", telemetryNote: "Simulated sensor feed · values are mock data and are not a diagnosis." },
  hi: { brandTagline: "स्वस्थ संबंध", earlyWarning: "पशु-मित्र शुरुआती चेतावनी", heroLineOne: "स्वस्थ गायें।", heroLineTwo: "सुकून भरी सुबह।", heroBody: "दिन में एक बार जांचें। जल्दी जानें। बेहतर देखभाल करें।", modelNote: "आज की रीडिंग से मॉडल अपडेट", simulatedFeed: "सिम्युलेटेड सेंसर फीड", milkCheck: "आज की दूध जांच", hardwareNote: "हार्डवेयर प्रोटोटाइप विकास में", conductivity: "विद्युत चालकता", conductivityNote: "दूध की चालकता · संक्रमण में बढ़ती है", temperature: "दूध का तापमान", temperatureNote: "दूसरा संकेत · गलत चेतावनी कम करने में मदद", battery: "सेंसर बैटरी", batteryNote: "सक्रिय · बैटरी धीरे घटती है", staleNote: "सेंसर जवाब नहीं दे रहा", telemetryNote: "सिम्युलेटेड सेंसर फीड · ये नकली मान हैं और निदान नहीं हैं।" },
  mr: { brandTagline: "निरोगी नाती", earlyWarning: "पशु-मित्र लवकर इशारा", heroLineOne: "निरोगी गायी.", heroLineTwo: "शांत सकाळी.", heroBody: "दिवसातून एकदा तपासा. लवकर जाणून घ्या. चांगली काळजी घ्या.", modelNote: "आजच्या रीडिंगमधून मॉडेल अपडेट", simulatedFeed: "सिम्युलेटेड सेन्सर फीड", milkCheck: "आजची दूध तपासणी", hardwareNote: "हार्डवेअर प्रोटोटाइप विकासात", conductivity: "विद्युत चालकता", conductivityNote: "दुधाची चालकता · संसर्गात वाढते", temperature: "दुधाचे तापमान", temperatureNote: "दुय्यम संकेत · चुकीच्या सूचना कमी करण्यास मदत", battery: "सेन्सर बॅटरी", batteryNote: "कार्यरत · बॅटरी हळूहळू कमी होते", staleNote: "सेन्सर प्रतिसाद देत नाही", telemetryNote: "सिम्युलेटेड सेन्सर फीड · ही बनावट मूल्ये आहेत, निदान नाही." },
  gu: { brandTagline: "સ્વસ્થ જોડાણો", earlyWarning: "પશુ-મિત્ર વહેલી ચેતવણી", heroLineOne: "સ્વસ્થ ગાયો.", heroLineTwo: "શાંત સવાર.", heroBody: "દિવસમાં એક વાર તપાસો. વહેલું જાણો. સારી સંભાળ રાખો.", modelNote: "આજના રીડિંગથી મોડેલ અપડેટ", simulatedFeed: "સિમ્યુલેટેડ સેન્સર ફીડ", milkCheck: "આજની દૂધ તપાસ", hardwareNote: "હાર્ડવેર પ્રોટોટાઇપ વિકાસમાં", conductivity: "વિદ્યુત વાહકતા", conductivityNote: "દૂધની વાહકતા · ચેપમાં વધે છે", temperature: "દૂધનું તાપમાન", temperatureNote: "બીજો સંકેત · ખોટી સૂચનાઓ ઘટાડે છે", battery: "સેન્સર બેટરી", batteryNote: "કાર્યરત · બેટરી ધીમે ઘટે છે", staleNote: "સેન્સર જવાબ આપતું નથી", telemetryNote: "સિમ્યુલેટેડ સેન્સર ફીડ · આ નકલી મૂલ્યો છે, નિદાન નથી." },
  pa: { brandTagline: "ਸਿਹਤਮੰਦ ਜੋੜ", earlyWarning: "ਪਸ਼ੂ-ਮਿੱਤਰ ਜਲਦੀ ਚੇਤਾਵਨੀ", heroLineOne: "ਤੰਦਰੁਸਤ ਗਾਵਾਂ।", heroLineTwo: "ਸੁਖਦ ਸਵੇਰਾਂ।", heroBody: "ਦਿਨ ਵਿੱਚ ਇੱਕ ਵਾਰ ਜਾਂਚੋ। ਜਲਦੀ ਜਾਣੋ। ਚੰਗੀ ਦੇਖਭਾਲ ਕਰੋ।", modelNote: "ਅੱਜ ਦੀਆਂ ਰੀਡਿੰਗਾਂ ਨਾਲ ਮਾਡਲ ਅੱਪਡੇਟ", simulatedFeed: "ਸਿਮੂਲੇਟਡ ਸੈਂਸਰ ਫੀਡ", milkCheck: "ਅੱਜ ਦੀ ਦੁੱਧ ਜਾਂਚ", hardwareNote: "ਹਾਰਡਵੇਅਰ ਪ੍ਰੋਟੋਟਾਈਪ ਵਿਕਾਸ ਵਿੱਚ", conductivity: "ਬਿਜਲੀ ਚਾਲਕਤਾ", conductivityNote: "ਦੁੱਧ ਦੀ ਚਾਲਕਤਾ · ਇਨਫੈਕਸ਼ਨ ਵਿੱਚ ਵਧਦੀ ਹੈ", temperature: "ਦੁੱਧ ਦਾ ਤਾਪਮਾਨ", temperatureNote: "ਦੂਜਾ ਸੰਕੇਤ · ਗਲਤ ਸੂਚਨਾਵਾਂ ਘਟਾਉਂਦਾ ਹੈ", battery: "ਸੈਂਸਰ ਬੈਟਰੀ", batteryNote: "ਚੱਲ ਰਹੀ · ਬੈਟਰੀ ਹੌਲੀ ਘਟਦੀ ਹੈ", staleNote: "ਸੈਂਸਰ ਜਵਾਬ ਨਹੀਂ ਦੇ ਰਿਹਾ", telemetryNote: "ਸਿਮੂਲੇਟਡ ਸੈਂਸਰ ਫੀਡ · ਇਹ ਨਕਲੀ ਮੁੱਲ ਹਨ, ਨਿਦਾਨ ਨਹੀਂ." },
  kn: { brandTagline: "ಆರೋಗ್ಯಕರ ಸಂಪರ್ಕಗಳು", earlyWarning: "ಪಶು-ಮಿತ್ರ ಮುನ್ನೆಚ್ಚರಿಕೆ", heroLineOne: "ಆರೋಗ್ಯಕರ ಹಸುಗಳು.", heroLineTwo: "ಶಾಂತ ಬೆಳಗ್ಗೆಗಳು.", heroBody: "ದಿನಕ್ಕೆ ಒಮ್ಮೆ ಪರೀಕ್ಷಿಸಿ. ಬೇಗ ತಿಳಿಯಿರಿ. ಉತ್ತಮ ಆರೈಕೆ ಮಾಡಿ.", modelNote: "ಇಂದಿನ ರೀಡಿಂಗ್‌ಗಳಿಂದ ಮಾದರಿ ನವೀಕರಿಸಲಾಗಿದೆ", simulatedFeed: "ಸಿಮ್ಯುಲೇಟೆಡ್ ಸೆನ್ಸರ್ ಫೀಡ್", milkCheck: "ಇಂದಿನ ಹಾಲಿನ ಪರೀಕ್ಷೆ", hardwareNote: "ಹಾರ್ಡ್‌ವೇರ್ ಮಾದರಿ ಅಭಿವೃದ್ಧಿಯಲ್ಲಿದೆ", conductivity: "ವಿದ್ಯುತ್ ವಾಹಕತೆ", conductivityNote: "ಹಾಲಿನ ವಾಹಕತೆ · ಸೋಂಕಿನಲ್ಲಿ ಹೆಚ್ಚುತ್ತದೆ", temperature: "ಹಾಲಿನ ತಾಪಮಾನ", temperatureNote: "ದ್ವಿತೀಯ ಸಂಕೇತ · ತಪ್ಪು ಎಚ್ಚರಿಕೆ ಕಡಿಮೆ ಮಾಡುತ್ತದೆ", battery: "ಸೆನ್ಸರ್ ಬ್ಯಾಟರಿ", batteryNote: "ಕಾರ್ಯನಿರ್ವಹಣೆ · ಬ್ಯಾಟರಿ ನಿಧಾನವಾಗಿ ಕಡಿಮೆಯಾಗುತ್ತದೆ", staleNote: "ಸೆನ್ಸರ್ ಪ್ರತಿಕ್ರಿಯಿಸುತ್ತಿಲ್ಲ", telemetryNote: "ಸಿಮ್ಯುಲೇಟೆಡ್ ಸೆನ್ಸರ್ ಫೀಡ್ · ಇವು ಮಾದರಿ ಮೌಲ್ಯಗಳು, ರೋಗನಿರ್ಣಯವಲ್ಲ." },
  ta: { brandTagline: "ஆரோக்கியமான இணைப்புகள்", earlyWarning: "பசு-மித்ரா முன் எச்சரிக்கை", heroLineOne: "ஆரோக்கியமான மாடுகள்.", heroLineTwo: "அமைதியான காலைகள்.", heroBody: "ஒரு நாளில் ஒருமுறை சரிபார்க்கவும். விரைவில் அறியவும். சிறப்பாக பராமரிக்கவும்.", modelNote: "இன்றைய வாசிப்புகளிலிருந்து மாதிரி புதுப்பிக்கப்பட்டது", simulatedFeed: "உருவகப்படுத்தப்பட்ட சென்சார் ஊட்டம்", milkCheck: "இன்றைய பால் சோதனை", hardwareNote: "வன்பொருள் முன்மாதிரி உருவாக்கத்தில்", conductivity: "மின் கடத்துத்திறன்", conductivityNote: "பாலின் கடத்துத்திறன் · தொற்றில் அதிகரிக்கும்", temperature: "பாலின் வெப்பநிலை", temperatureNote: "இரண்டாம் அறிகுறி · தவறான எச்சரிக்கைகளை குறைக்கும்", battery: "சென்சார் பேட்டரி", batteryNote: "செயலில் · பேட்டரி மெதுவாக குறையும்", staleNote: "சென்சார் பதிலளிக்கவில்லை", telemetryNote: "உருவகப்படுத்தப்பட்ட சென்சார் ஊட்டம் · இவை மாதிரி மதிப்புகள், நோயறிதல் அல்ல." },
  te: { brandTagline: "ఆరోగ్యకరమైన అనుసంధానాలు", earlyWarning: "పశు-మిత్ర ముందస్తు హెచ్చరిక", heroLineOne: "ఆరోగ్యమైన ఆవులు.", heroLineTwo: "ప్రశాంతమైన ఉదయాలు.", heroBody: "రోజుకు ఒకసారి తనిఖీ చేయండి. త్వరగా తెలుసుకోండి. మెరుగైన సంరక్షణ చేయండి.", modelNote: "నేటి రీడింగ్‌లతో మోడల్ నవీకరించబడింది", simulatedFeed: "సిమ్యులేటెడ్ సెన్సర్ ఫీడ్", milkCheck: "నేటి పాలు తనిఖీ", hardwareNote: "హార్డ్‌వేర్ నమూనా అభివృద్ధిలో ఉంది", conductivity: "విద్యుత్ వాహకత", conductivityNote: "పాల వాహకత · సంక్రమణలో పెరుగుతుంది", temperature: "పాల ఉష్ణోగ్రత", temperatureNote: "ద్వితీయ సంకేతం · తప్పుడు హెచ్చరికలను తగ్గిస్తుంది", battery: "సెన్సర్ బ్యాటరీ", batteryNote: "పనిచేస్తోంది · బ్యాటరీ నెమ్మదిగా తగ్గుతుంది", staleNote: "సెన్సర్ స్పందించడం లేదు", telemetryNote: "సిమ్యులేటెడ్ సెన్సర్ ఫీడ్ · ఇవి నమూనా విలువలు, నిర్ధారణ కాదు." },
};
export const trendBodyByLanguage: Record<Language, string> = {
  en: "Lakshmi’s risk rose over the last 5 days. This is an early warning, before visible signs.",
  hi: "लक्ष्मी का जोखिम पिछले 5 दिनों में बढ़ा है। यह दिखाई देने वाले लक्षणों से पहले की चेतावनी है।",
  mr: "लक्ष्मीचा धोका मागील ५ दिवसांत वाढला आहे. दिसणारी लक्षणे येण्यापूर्वीचा हा इशारा आहे.",
  gu: "લક્ષ્મીનું જોખમ છેલ્લા 5 દિવસમાં વધ્યું છે. દેખાતા લક્ષણો પહેલાંની આ વહેલી ચેતવણી છે.",
  pa: "ਲਕਸ਼ਮੀ ਦਾ ਖਤਰਾ ਪਿਛਲੇ 5 ਦਿਨਾਂ ਵਿੱਚ ਵਧਿਆ ਹੈ। ਇਹ ਦਿਖਾਈ ਦੇਣ ਵਾਲੇ ਲੱਛਣਾਂ ਤੋਂ ਪਹਿਲਾਂ ਦੀ ਚੇਤਾਵਨੀ ਹੈ.",
  kn: "ಲಕ್ಷ್ಮಿಯ ಅಪಾಯವು ಕಳೆದ 5 ದಿನಗಳಲ್ಲಿ ಹೆಚ್ಚಾಗಿದೆ. ಕಾಣುವ ಲಕ್ಷಣಗಳಿಗಿಂತ ಮುಂಚಿನ ಮುನ್ನೆಚ್ಚರಿಕೆ ಇದು.",
  ta: "லட்சுமியின் ஆபத்து கடந்த 5 நாட்களில் அதிகரித்துள்ளது. காணக்கூடிய அறிகுறிகளுக்கு முன் வரும் எச்சரிக்கை இது.",
  te: "లక్ష్మి ప్రమాదం గత 5 రోజుల్లో పెరిగింది. కనిపించే లక్షణాలకు ముందే వచ్చే హెచ్చరిక ఇది.",
};

export const riskMeta = {
  high: { label: "High risk", color: "red", icon: CircleAlert },
  medium: { label: "Watch closely", color: "yellow", icon: AlertCircle },
  low: { label: "Low risk", color: "green", icon: CheckCircle2 },
} as const;

export function formatRisk(risk: Risk, lang: Language) {
  const labels = localizedCopy[lang];
  return risk === "high" ? labels.high : risk === "medium" ? labels.medium : labels.low;
}








